mesop-dev/mesop

- scripts/cli.sh
- scripts/run_py_dev.sh
- scripts/run_web_dev.sh
Fix scripts so that they run on linux instead of just osx
> Linux support

- docs/guides/components.md
- docs/guides/troubleshooting.md
- docs/stylesheets/extra.css
- mesop/components/audio/audio.py
- mesop/components/badge/badge.py
- mesop/components/box/box.py
- mesop/components/button/button.py
- mesop/components/checkbox/checkbox.py
- mesop/components/divider/divider.py
- mesop/components/icon/icon.py
- mesop/components/image/image.py
- mesop/components/input/input.py
- mesop/components/progress_bar/progress_bar.py
- mesop/components/progress_spinner/progress_spinner.py
- mesop/components/radio/radio.py
- mesop/components/select/select.py
- mesop/components/sidenav/sidenav.py
- mesop/components/slide_toggle/slide_toggle.py
- mesop/components/slider/slider.py
- mesop/components/text/text.py
- mesop/components/tooltip/tooltip.py
- mkdocs.yml
- Update component API reference to link to component key doc section
> Document component key (closes #74)

- mesop/server/BUILD
- mesop/server/colab_run.py
- mesop/server/colab_run_test.py
- mesop/server/wsgi_app.py
- mesop/server/wsgi_app_test.py
- Adds unit tests to avoid future regressions
> Fix logic for setting debug mode from colab_run and wsgi_app (closes #83)

- mesop/component_helpers/style.py
- mesop/components/box/e2e/box_app.py
- mesop/examples/index.py
> Create shorthands for Margin, Padding, and Border

- mesop/components/markdown/e2e/markdown_app.py
- mesop/components/markdown/markdown.ng.html
- mesop/components/markdown/markdown.ts
I forgot to wire the style attribute for markdown previously
> Plumb style for markdown

- mesop/component_helpers/style.py
- mesop/protos/ui.proto
- mesop/web/src/utils/styles.ts
> Add aspect_ratio and overflow_wrap to Style

- mesop/components/input/e2e/input_test.ts
- mesop/examples/generator.py
- mesop/examples/playground.py
- mesop/tests/e2e/buttons_test.ts
- mesop/tests/e2e/conditional_event_handler_test.ts
- mesop/tests/e2e/generator_test.ts
- mesop/tests/e2e/navigation_test.ts
Fixes #64. Long overdue - provides more e2e test coverage for core functionality.
> Add e2e tests

- docs/internal/publishing.md
- mesop/version.py
- scripts/pip.sh
- scripts/smoketest_app/main.py
Drive-by: tweak pip.sh to be more convenient
Closes #164
> Cut v0.5 release

- mesop/__init__.py
- mesop/components/table/e2e/table_app.py
- mesop/components/table/e2e/table_test.ts
- mesop/components/table/table.ng.html
- mesop/components/table/table.proto
- mesop/components/table/table.py
- mesop/components/table/table.ts
> Add sticky headers and columns for Table component

- mesop/components/table/e2e/table_test.ts
> Skip flaky test for table component: sticky header & column

- mesop/bin/bin.py
> Hot reload labs component when using `mesop` CLI

- README.md
- docs/index.md
- docs/stylesheets/extra.css
> De-emphasize visual editor since it's not support is not great now

- docs/components/code.md
- mesop/BUILD
- mesop/__init__.py
- mesop/components/code/BUILD
- mesop/components/code/code.py
- mesop/examples/__init__.py
- mesop/examples/code.py
- mkdocs.yml
> Create code component

- mesop/bin/bin.py
> Make hot reloading more robust by only watching necessary files

- mesop/version.py
I accidentally released v0.5.4 to PyPI without a git commit... so skipping to v0.5.5
> Bump v0.5.5

- demo/main.py
To fix the issue we use four backticks for code fence to avoid conflicts with backticks being used within the displayed code.
Fixes #249
> Fix code block rendering in demo app

- mesop/components/slider/e2e/slider_app.py
- mesop/components/slider/slider.ng.html
- mesop/components/slider/slider.py
- mesop/components/slider/slider.ts
> Support style property for slider

- demo/code_demo.py
- demo/main.py
The code demo was not rendering correctly since there is an existing code module in Python.
> Fix code demo rendering.

- demo/main.py
- demo/select_demo.py
The select demo was not rendering correctly since there is an existing module in Python.
> Fix select demo rendering.

- demo/basic_animation.py
- demo/main.py
Mostly just for fun. But it occurred to me that the event yielding could be used to perform timed updates to the UI, which would make things like rending temporary toasts/flash type messages possible. Sort of like the old school jquery animations that could be applied. In the end not that practical, but kind of fun.
> Add basic animation demo

- .pre-commit-config.yaml
- mesop/examples/testing/complex_layout.py
- mesop/pip_package/deterministic_tar_gz.py
- mesop/server/static_file_serving.py
- scripts/scaffold_component.py
It was fighting some of the formatting changes I was making (due to a version skew between the version of the Ruff via VS code extension and the pre-commit Ruff)
> Upgrade ruff pre-commit hook

- mesop/cli/cli.py
- mesop/component_helpers/helper.py
- mesop/web/src/app/editor/BUILD
- mesop/web/src/component_renderer/type_to_component.ts
I think we will need some custom components for our hackathon that aren't yet ready to be public APIs, I will open a draft PR to demonstrate this.
Related to #95
> Setup APIs to allow custom component downstream

- mesop/server/static_file_serving.py
This is needed after #270 which set CSP:
- Set nonce for live reload script.
- Set connect-src for the EventSource network connection to the live reload server.
> Fix live reload for downstream

- docs/guides/web_security.md
- mesop/__init__.py
- mesop/examples/__init__.py
- mesop/examples/allowed_iframe_parents.py
- mesop/features/page.py
- mesop/runtime/BUILD
- mesop/runtime/__init__.py
- mesop/runtime/runtime.py
- mesop/security/BUILD
- mesop/security/security_policy.py
- mesop/server/server.py
- mesop/server/static_file_serving.py
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-allowed-iframe-parents.txt
- mesop/tests/e2e/web_security_test.ts
- mkdocs.yml
- In editor mode, allow any origin to iframe Mesop (in particular because Colab iframes content like Mesop in a randomly generated origin, but also to make local development easier, where you may want to iframe from another localhost port).
- In prod mode, allow the self origin and any allow-listed origins for that particular page.
- Adds docs
Fixes #271.
> Enable allow-listing parent origins for iframing

- mesop/server/server.py
> Protect against CSRF by checking origin of POST request

- docs/internal/development.md
- docs/internal/testing.md
- mkdocs.yml
Anything else that you think should be refreshed?
> Improve our internal documentation

- docs/guides/commands.md
- mesop/__init__.py
- mesop/commands/navigate.py
- mesop/commands/scroll_into_view.py
- mesop/examples/__init__.py
- mesop/examples/scroll_into_view.py
- mesop/protos/ui.proto
- mesop/runtime/context.py
- mesop/tests/e2e/scroll_into_view_test.ts
- mesop/web/src/component_renderer/component_renderer.ng.html
- mesop/web/src/component_renderer/component_renderer.ts
- mesop/web/src/services/channel.ts
- mesop/web/src/shell/shell.ts
- mkdocs.yml
Closes #106.
- Also adds additional documentation for the existing `navigate` command.
> Add `scroll_into_view` command

- demo/llm_playground.py
- demo/llm_rewriter.py
- mesop/examples/e2e/chat_test.ts
- mesop/labs/chat.py
- Add on enter event for llmrewriter and chat
- Move button to same line as text input for llm_rewriter and chat
- Set default value for sliders in llm playground
- Allow text input to control sliders in llm playground
> Minor updates to demos and labs.chat

- docs/guides/pages.md
- mesop/__init__.py
- mesop/events/__init__.py
- mesop/events/events.py
- mesop/examples/__init__.py
- mesop/examples/docs/__init__.py
- mesop/examples/docs/on_load.py
- mesop/examples/docs/on_load_generator.py
- mesop/examples/navigate_advanced.py
- mesop/examples/on_load.py
- mesop/examples/on_load_generator.py
- mesop/features/page.py
- mesop/runtime/__init__.py
- mesop/runtime/runtime.py
- mesop/server/BUILD
- mesop/server/server.py
- mesop/tests/e2e/on_load_test.ts
- mesop/warn/BUILD
- mesop/warn/__init__.py
- mesop/warn/warn.py
> Provide an `on_load` hook for page load

- mesop/web/src/services/channel.ts
No longer needed since dev mode has been removed
> Remove DEV_SERVER_HOST

- mesop/exceptions/format_traceback.py
> Ensure stack trace does not show stale code

- docs/internal/publishing.md
@richard-to I think it would be good for you to do a pip release, just so you're familiar with it. Let me know if you have any questions! (I will also need to grant you PyPI access).
Closes #327.
> Add steps for creating an RC for pip publishing process

- docs/api/viewport_size.md
- mesop/__init__.py
- mesop/examples/__init__.py
- mesop/examples/viewport_size.py
- mesop/features/viewport_size.py
- mesop/protos/ui.proto
- mesop/runtime/context.py
- mesop/server/server.py
- mesop/tests/e2e/viewport_size_test.ts
- mesop/web/src/services/channel.ts
- mesop/web/src/shell/shell.ts
- mesop/web/src/utils/viewport_size.ts
- mkdocs.yml
> Support responsive/adaptive design with viewport size

- WORKSPACE
> chore: update WORKSPACE

- mesop/cli/cli.py
- mesop/runtime/runtime.py
> Fix double-registration of stateclass when --reload_demo_modules

- demo/markdown_editor.py
Remove the use of conditional in page to set initial state. Use default factory which is preferable.
> Use default factory to in notes for markdown demo

- demo/audio.py
- mesop/components/audio/audio.ng.html
- mesop/components/audio/audio.proto
- mesop/components/audio/audio.py
- package.json
- tools/defaults.bzl
- yarn.lock
This change implemented an `autoplay` function for audio component, as mentioned in #299.
I have added autoplay as a Boolean variable defaulted to `False`.
If autoplay feature is required, one have to call the function like,
```
me.audio(
src="https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3",
autoplay = True
)
```
> Implement autoplay option for audio component

- mesop/pip_package/setup.py
> Correct the Python version requirement for pip package

- mesop/component_helpers/helper.py
> Make insert_web_component kw_args only

- mesop/cli/cli.py
- mesop/colab/colab_run.py
- mesop/server/wsgi_app.py
- mesop/utils/host_util.py
> Use ipv4 host if ipv6 is not available

- docs/api/commands/navigate.md
- mesop/examples/navigate.py
> added proper example for navigate api

- mesop/dataclass_utils/dataclass_utils.py
- mesop/dataclass_utils/dataclass_utils_test.py
- mesop/examples/__init__.py
- mesop/examples/dict_state.py
- mesop/tests/e2e/state_test.ts
> Fix deserializing dict for stateclass

- mesop/server/static_file_serving.py
> Fix mimetype for JS files

- docs/api/config.md
- docs/guides/deployment.md
- docs/guides/state_management.md
- mkdocs.yml
- Adds config section to describe how to set memory backend
- Update state management section to reference memory backend
- Update deployment section to include session affinity note
Ref #62
> Update docs with info about state sessions

- demo/box.py
- mesop/component_helpers/style.py
- tools/defaults.bzl
> Added More Borders

- mesop/components/plot/plot.py
Ref: https://github.com/google/mesop/issues/433
> Render SVG image with plot component

- docs/api/config.md
- docs/components/index.md
- docs/internal/hot_reload.md
- Fix old Style API usage
- Fix link on hot reloading
- Remove outdated line in config page
> Minor documentation fixes

- mesop/components/input/input.ts
Forgot to add this change to previous pull request for IME fix.
> Follow up on code review for ime change

- mesop/runtime/runtime.py
Context: https://github.com/pallets/flask/discussions/5507
> Namespace g attribute

- mesop/component_helpers/helper.py
Analysis: https://colab.research.google.com/drive/1KcAG0iQJ-vor3KQw7A-CFKW85hPb1_Bg?usp=sharing
Fixes #410
> Set LRU cache for compute_fn_id

- mesop/bin/bin.py
> Add `mesop init` CLI command

- mesop/examples/web_component/BUILD
- mesop/examples/web_component/__init__.py
- mesop/examples/web_component/code_mirror_editor/BUILD
- mesop/examples/web_component/code_mirror_editor/code_mirror_editor_app.py
- mesop/examples/web_component/code_mirror_editor/code_mirror_editor_component.js
- mesop/examples/web_component/code_mirror_editor/code_mirror_editor_component.py
This is just a basic integration mainly to learn how to write a web component with Mesop. But also planning to use Code Mirror for the PyRun editor.
> Add web component that integrates Code Mirror

- demo/link.py
- demo/main.py
- docs/components/link.md
- mesop/BUILD
- mesop/__init__.py
- mesop/components/link/BUILD
- mesop/components/link/e2e/BUILD
- mesop/components/link/e2e/__init__.py
- mesop/components/link/e2e/link_app.py
- mesop/components/link/e2e/link_test.ts
- mesop/components/link/link.ng.html
- mesop/components/link/link.proto
- mesop/components/link/link.py
- mesop/components/link/link.scss
- mesop/components/link/link.ts
- mesop/example_index.py
- mesop/examples/BUILD
- mesop/web/src/component_renderer/BUILD
- mesop/web/src/component_renderer/type_to_component.ts
- mkdocs.yml
> Add link component

- mesop/web/src/shell/shell.ts
> Debounce resize event

- docs/components/autocomplete.md
> Fix docs for autocomplete

- demo/dialog.py
- demo/headers.py
- demo/snackbar.py
Updates dialog, headers, and snackbar to be compliant with dark mode. I was updating these in prompt tuner app, so figured I'd update them here too.
Overall, using theme colors wasn't too bad.
> Update a few patterns for dark mode

- demo/main.py
- mesop/web/src/app/styles.scss
Also: minor UI tweaks to demo gallery - remove GitHub logo which looks a little weird; and format the repo link more nicely.
Fixes #699.
> Support dark theme: syntax highlighting + demo gallery

- docs/api/commands/focus_component.md
- mesop/__init__.py
- mesop/commands/focus_component.py
- mesop/examples/__init__.py
- mesop/examples/focus_component.py
- mesop/labs/chat.py
- mesop/protos/ui.proto
- mesop/runtime/context.py
- mesop/tests/e2e/focus_component_test.ts
- mesop/web/src/shell/shell.ts
- mkdocs.yml
Add focus command and adds focus to mel.chat
Ref: https://github.com/google/mesop/issues/609
> Add focus command.

- mesop/web/src/app/editor/index.html
- mesop/web/src/app/prod/index.html
> Remove loading text from index.html

- mesop/version.py
- scripts/smoketest_app/simple_slot_app.py
Update smoketest app with security policy (see: #723)
> Bump to v0.11.0

- showcase/main.py
- Add a "add to showcase" button in sidenav
- UX polish
> Fine-tune UI for showcase

- mesop/examples/__init__.py
- mesop/examples/event_handler_error.py
- mesop/tests/e2e/event_handler_error_test.ts
- mesop/web/src/shell/shell.ts
> Fix race condition where the error box didn't always display

- docs/guides/testing.md
- mkdocs.yml
Example repo: https://github.com/wwwillchen/mesop-playwright-testing
Fixes #297.
> Add testing guide

- mesop/examples/navigate_advanced.py
- mesop/tests/e2e/dom_state_test.ts
- mesop/web/src/component_renderer/component_renderer.ts
> Ensure DOM state is reset across pages

- ai/docbot/docs_index.py
- ai/docbot/main.py
> docbot: do direct retrieval for input

- biome.json
- mesop/components/audio/audio.ts
- mesop/components/autocomplete/autocomplete.ts
- mesop/components/image/image.ts
- mesop/components/input/input.ts
- mesop/components/link/link.ts
- mesop/components/sidenav/sidenav.ts
- mesop/components/video/video.ts
- mesop/examples/e2e/theme_density_test.ts
- mesop/examples/web_component/firebase_auth/firebase_auth_component.js
- mesop/examples/web_component/plotly/plotly_component.js
- mesop/examples/web_component/slot/outer_component.js
- mesop/examples/web_component/svg_icon/svg_icon_component.js
- mesop/tests/e2e/concurrency/state_test.ts
- mesop/tests/e2e/query_params_test.ts
- mesop/tests/e2e/web_components/slot_test.ts
- mesop/web/src/component_renderer/component_renderer.ts
- mesop/web/src/dev_tools/component_tree/component_tree.ts
- mesop/web/src/dev_tools/editor_panel/editor_panel.ts
- mesop/web/src/services/channel.ts
- mesop/web/src/services/error_dialog_service.ts
- mesop/web/src/shell/shell.ts
- mesop/web/src/utils/query_params_spec.ts
- package.json
- yarn.lock
https://github.com/google/mesop/commit/7400eb73af0a83713dcf46d62722a79b1b3b6815 erroneously added biome which is another npm dependency which shadowed the actual biome dependency we use for linting. Thus, we were effectively not linting our TS files for a couple months.
> Fix biome by removing erroneous biome dependency

- mesop/dataclass_utils/dataclass_utils.py
- mesop/dataclass_utils/dataclass_utils_test.py
- mesop/dataclass_utils/diff_state_test.py
- mesop/examples/testing/__init__.py
- mesop/examples/testing/set_serialize.py
- mesop/tests/e2e/set_serialize_test.ts
- mesop/web/src/utils/diff.ts
- mesop/web/src/utils/diff_state_spec.ts
This change adds support for using sets in State classes.
- Closes #770 
- Ref #387
> Allow sets in State classes.

- mesop/web/src/utils/diff.ts
Factored out some of the duplication from the add remove set/array functions all used basically the same loop.
> Refactor some code duplication from diff.ts

- mesop/component_helpers/style.py
- mesop/protos/ui.proto
- mesop/web/src/utils/styles.ts
> Add more style properties

- mesop/__init__.py
- mesop/server/wsgi_app.py
> Export `create_wsgi_app` so Mesop apps can be mounted to other servers

- mesop/web/src/editor_toolbar/editor_toolbar_service.ts
This way if you refresh, you can still look up the prompt history and revert changes. Particularly useful since you need to reload due to state changes.
> Persist prompt interactions into sessionStorage

- mesop/web/src/editor_toolbar/editor_toolbar.ng.html
- mesop/web/src/editor_toolbar/editor_toolbar.ts
Drive-by: add tooltip to send button
> Require prompt minimum length (4 chars)

- mesop/examples/web_component/firebase_auth/firebase_auth_app.py
- mesop/examples/web_component/firebase_auth/firebase_auth_component.js
> Fix firebase auth example

- demo/fancy_chat.py
- demo/main.py
Features:
- Mobile support
- Dark mode
- Styled input
- New chat
- Rate message
- Regenerate message
- Chats history
- Scroll to
- Focus input
TODO:
- Text / Image output support
- Shift + Enter
- Update to use partial functions
- Copy / Paste
Closes #712
> Add Fancy chat example

- showcase/main.py
> Add Multimodal Embeddings Retail Search to showcase

- ai/src/ai/common/executor.py
- ai/src/ai/console/pages/evals_page.py
- ai/src/ai/offline_common/eval.py
- Supports Gemini and Fireworks as providers.
- Minor tweaks to console UI and reading the file
> Update AI console - support Gemini, Fireworks and temperature + tweaks

- demo/autocomplete.py
- mesop/components/autocomplete/autocomplete.ts
- mesop/components/autocomplete/e2e/autocomplete_app.py
- mesop/components/autocomplete/e2e/autocomplete_test.ts
> Set default value on autocomplete

- ai/src/ai/common/example.py
- ai/src/ai/common/model_validators.py
Starting to play around with the AI console crud app. Overall, pretty cool. But also some rough edges in the UX. This PR is mainly improves the pydantic validation for the line number target field a bit.
> Add additional validation for line_number_target

- demo/form_billing.py
- demo/form_profile.py
- demo/main.py
Just some examples to show ways to layout forms. Will add these to goldens as well later.
> Add basic form examples.

- ai/src/ai/common/entity_store.py
- ai/src/ai/common/example.py
- ai/src/ai/common/model.py
- ai/src/ai/common/model_validators.py
- ai/src/ai/common/producer.py
- ai/src/ai/common/prompt_context.py
- ai/src/ai/common/prompt_fragment.py
Added some more basic validation to console forms.
Ref #953
> Add some more pydantic validation to AI console

- ai/README.md
- ai/src/ai/common/diff.py
- ai/src/ai/common/example.py
- ai/src/ai/common/executor.py
- ai/src/ai/console/pages/evals_page.py
- ai/src/ai/console/pages/expected_examples_page.py
- ai/src/ai/console/pages/golden_examples_page.py
- ai/src/ai/console/pages/models_page.py
- ai/src/ai/console/pages/producers_page.py
- ai/src/ai/console/pages/prompt_contexts_page.py
- ai/src/ai/console/pages/prompt_fragments_page.py
- ai/src/ai/offline_common/golden_dataset.py
- ai/src/service.py
- mesop/web/src/editor_toolbar/editor_toolbar_service.ts
- pyproject.toml
- Also includes llama3 prompt formatter (required for together fine-tuning: https://docs.together.ai/docs/fine-tuning-task-specific-sequences#llama-3-instruct)
- Adds timestamps for examples #938
> Update AI: fix save-interaction for goldens; add together provider

- demo/input.py
- mesop/components/autocomplete/BUILD
- mesop/components/date_range_picker/BUILD
- mesop/components/defs.bzl
- mesop/components/input/BUILD
- mesop/components/slider/BUILD
Rxjs dep is used for the debounce behavior.
Closes #997
> Add rxjs dep to date range picker

- demo/autocomplete.py
- demo/input.py
- demo/select_demo.py
- demo/textarea.py
- mesop/components/select/e2e/select_app_multiple.py
- mesop/components/select/e2e/select_test.ts
- mesop/components/select/select.ng.html
- mesop/components/select/select.proto
- mesop/components/select/select.py
- mesop/components/select/select.ts
Drive by adjustments:
- Add appearance property to select
- Update autocomplete/input/textarea/select to use outline appearance.
Closes #681
> Fix bug where multiple select values could not be initialized.

- mesop/web/src/services/channel.ts
Noticed this bug in my personal app where on hot reload the theme settings wasn't getting properly set
> Set theme settings in hot reload

- docs/internal/publishing.md
It's a little inconvenient but it looks like we can't get an automated PR review from snyk with the free plan. Maybe there's another service we can use?
@richard-to - I've invited you to the snyk org (check your email)
> Add step to check security dashboard on publishing

- mesop/web/src/error/error_box.scss
- mesop/web/src/error/error_box.ts
- mesop/web/src/shell/shell.ts
> Fix server error dialog UI

- mesop/dataclass_utils/diff_state_test.py
- mesop/server/state_session_test.py
Replace "Optional[...]" with "... | None"
> Consistent type hints for Optional

- mesop/examples/web_component/BUILD
- mesop/examples/web_component/__init__.py
- mesop/examples/web_component/google_maps/BUILD
- mesop/examples/web_component/google_maps/google_maps_app.py
- mesop/examples/web_component/google_maps/google_maps_component.js
- mesop/examples/web_component/google_maps/google_maps_component.py
> Note: This will most likely require linting to be done. If there is a linting tool I should use please let me know.
> Add Google Maps example web component

- mesop/dataclass_utils/dataclass_utils.py
Fix broken url.
Please merge this PR after approvals. Thanks
> docs: fix broken url

- mesop/web/src/services/channel.ts
Fixes #1232 
As noted in the bug, none of our tests really detect this flakiness on GitHub. I tested this downstream and it fixes the flakiness.
> Fix race condition by queueing message processing in Channel

- mesop/web/src/utils/diff_component_spec.ts
> chore: update diff_component_spec.ts

- mesop/component_helpers/helper.py
- mesop/components/button/button.proto
- mesop/components/button/button.ts
- mesop/web/src/component_renderer/component_renderer.ts
- Fixed incorrect use of onClick instead of onRightClick
- Remove right click usage on button which was not implemented
Ref #1272
> Fix bugs with right click

- mesop/server/server_utils.py
This small PR fixes the errors thrown in `mesop/server/server_utils.py`.
> Fix mesop server error messages

- showcase/main.py
- showcase/requirements.txt
Note: Had to shorten the description a bit to make sure the buttons didn't overlap with description text.
Closes #1305
> Add GenMedia Creative Studio to showcase
