mesop-dev/mesop

- mesop/component_helpers/style.py
- mesop/protos/ui.proto
The `flex-shrink` css property could not be set to 0 since Mesop will ignore styles that are "empty".
Normally this is fine, but `flex-shrink` defaults to 1, which means the "empty" state will make `flex-shrink` equal to 1. This means that 0 cannot be set for `flex-shrink`.
To resolve this, we can change the date type to a string in the UI proto.
Example:
```
import mesop as me
@me.page(path="/flex_shrink")
def main():
with me.box(style=me.Style(display="flex", flex_shrink="0")):
me.text("Testing flex shrink")
```
Also here's a screenshot to check that the property is being set correctly:
Fixes #69
> Allow `flex-shrink` to be set to 0.

- mesop/components/checkbox/checkbox.py
- mesop/components/progress_bar/progress_bar.py
- mesop/components/radio/radio.py
- mesop/components/select/select.py
- mesop/components/slide_toggle/slide_toggle.py
- mesop/components/slider/slider.py
- mesop/events/events.py
- mesop/key/key.py
> Make all (API-exposed) dataclass kw-only

- mesop/component_helpers/style.py
- mesop/protos/ui.proto
The columns property allows int/strs according to
https://developer.mozilla.org/en-US/docs/Web/CSS/columns
To test this change, I tested out the following code.
```
import mesop as me
@me.page(path="/columns")
def main():
with me.box(style=me.Style(columns="150px 3")):
me.text("first_column")
me.text("second_column")
with me.box(style=me.Style(columns=2)):
me.text("first_column")
me.text("second_column")
```
I also tried to update the columns component in labs.layout.py, but ran into an issue there trying to change the field definition to int | str. So for now, just left it as int.
This led to this error: `Mesop Internal Error: ('Unhandled param type', int | str, 'field_name', 'columns')`
Which leads to: mesop/mesop/editor/component_configs.py
It's probably related to the logic around …
> Allow columns CSS property to accept int/str vals.

- docs/components/text_to_image.md
- mesop/examples/__init__.py
- mesop/examples/text_to_image.py
- mesop/labs/__init__.py
- mesop/labs/text_to_image.py
- mkdocs.yml
Also adds an example usage of the function.
I kept the implementation the same as the text_io one. Mainly just copied the code and made a few adjustments. I just copied the code to make it easier for others to copy if they wanted to add more functionality.
Here is a sample screenshot that uses a transform function that just returns the same image every time (note: need to pick a a few sample images to use  and also host somewhere).
> Add a text to image IO function.

- mesop/cli/cli.py
- mesop/cli/dev_cli.py
- mesop/server/colab_run.py
- mesop/server/wsgi_app.py
Why? Running Colab (internally) requires IPv6, which isn't currently supported when using "0.0.0.0"
Using `::` ensures that this will work for for both IPv6 and IPv4 environments, according to:
- https://stackoverflow.com/a/21689979
Background:
- https://superuser.com/questions/515379/what-is-the-difference-between-and-0-0-0-0-from-the-netstat-an-output
- https://en.wikipedia.org/wiki/0.0.0.0?useskin=vector
Closes https://github.com/google/mesop/issues/102
> Switch to ipv6 host

- docs/components/chat.md
- mesop/examples/__init__.py
- mesop/examples/chat.py
- mesop/examples/e2e/chat_test.ts
- mesop/labs/__init__.py
- mesop/labs/chat.py
- mkdocs.yml
- playwright.config.ts
Also adds an example usage of the chat widget.
- Provide title
- Provide a bot name
- Can stream chat response
- When generating a response, new prompts cannot
- be sent
- Relatively responsive to device width
- Chat window does not scroll along with new text being added.
- Text input does not clear when pressing entering a prompt.
> Add simple chat widget function.

- build_defs/defaults.bzl
- build_defs/requirements.txt
- build_defs/requirements_lock.txt
- docs/components/table.md
- mesop/BUILD
- mesop/__init__.py
- mesop/cli/BUILD
- mesop/components/table/BUILD
- mesop/components/table/e2e/BUILD
- mesop/components/table/e2e/__init__.py
- mesop/components/table/e2e/table_app.py
- mesop/components/table/e2e/table_test.ts
- mesop/components/table/table.ng.html
- mesop/components/table/table.proto
- mesop/components/table/table.py
- mesop/components/table/table.ts
- mesop/example_index.py
- mesop/examples/BUILD
- mesop/web/src/component_renderer/BUILD
- mesop/web/src/component_renderer/type_to_component.ts
- mkdocs.yml
- packages.bzl
This change adds a barebones Angular table that can take a Pandas DataFrame as input.
Current issues:
- Table headers not bold
- Style support (haven't looked into this yet)
Example usage:
```
import pandas
import mesop as me
@me.page(path="/components/table/e2e/table_app")
def app():
with me.box(
style=me.Style(
padding=me.Padding(top=10, right=10, left=10, bottom=10), width=500
)
):
d = {
"Bools": [True, False],
"Ints": [3, 4],
"Floats": [2.3, 4.5],
"Strings": ["Hello", "World"],
}
df = pandas.DataFrame(data=d)
me.table(me.TableDataSourcePandasDataFrame(df=df))
```
Issue Reference: #75
> Add basic table with Pandas support

- docs/internal/development.md
Currently refers to a defunct build target.
> Update development.md to reference cli.venv

- docs/internal/publishing.md
- mesop/BUILD
- mesop/__init__.py
- mesop/pip_package/BUILD
- mesop/pip_package/build_pip_package.sh
- mesop/pip_package/setup.py
- mesop/pip_package/version.py
Fixes #104 
pip_package is a bit strangely organized (it was modeled after https://github.com/tensorflow/tensorboard/tree/master/tensorboard/pip_package)
> Add __version__ attribute so Mesop users can easily tell which version of Mesop they're using

- mesop/__init__.py
- mesop/exceptions/__init__.py
Closes #111.
This makes it possible for Mesop app developers to catch Mesop exceptions and having them all subclass from a single Mesop exception class also makes it more convenient to catch any kind of Mesop exception.
> Make MesopException the parent class of more specific mesop exceptions & expose as public API

- mesop/cli/execute_module.py
- mesop/cli/execute_module_test.py
This change separates the hot reloading logic for the mesop module and external app modules.
Before this fix, if the app module is outside of the mesop module, then changes to code in labs would not be reflected in the hot reload since the mesop directory is not also the app module.
> Update hot reloading logic in execute_module.py

- mesop/pip_package/BUILD
This breaks the downstream sync since it now depends on version.py inside pip_package
> Update BUILD in pip_package to not directly reference @rules_python

- mesop/web/src/app/styles.scss
Instead show a horizontal scrollbar to remain within the boundaries of the box.
The scroll bar appears, so that is an improvement, but it kind of looks like the text gets cut off since the code mark up gets rendered on a white background, so there's no delineation of where the code block actually ends width wize.
Some example screen shots:
> Make it so wide code examples do not overflow.

- scripts/setup_proto_py_modules.sh
@richard-to not sure if you've setup VS Code type-checking - there's [some instructions here](https://google.github.io/mesop/internal/development/#venv), but I just recently fixed it with this PR and this earlier docs fix: https://github.com/google/mesop/commit/11c8d36d98dbe2477c09224cd41ee22e2082ab15
> Fix setup_proto_py_modules.sh

- mesop/bin/bin.py
fixes #128 
drive-by: fix weird coding pattern from earlier.
> Fix imports when using mesop CLI bin.py

- mesop/dataclass_utils/BUILD
- mesop/dataclass_utils/dataclass_utils.py
- mesop/dataclass_utils/dataclass_utils_test.py
To fix this issue we add custom JSON encoding and decoding logic.
For most accurate serialization/deserialization, we use Pandas's built in JSON serialization (via to_json) with the "table" strategy. This is more verbose, but provides enough metadata to deserialize as close as possible to the original DataFrame.
To deserialize we use `pandas.read_json` with `orient="table"`.
One difference I've noticed so far is that pandas.NA becomes np.nan.
Ref: #117
> Fix state serialization bug with pandas.DataFrame.

- mesop/__init__.py
- mesop/components/table/e2e/table_app.py
- mesop/components/table/e2e/table_test.ts
- mesop/components/table/table.ng.html
- mesop/components/table/table.proto
- mesop/components/table/table.py
- mesop/components/table/table.ts
- mesop/protos/ui.proto
The table cell click event will return the column name and row Index which will allow us to refer back to the same row or column in the Pandas data frame.
Ref: #118
> Add on table cell click event

- mesop/components/defs.bzl
- mesop/components/radio/BUILD
- mesop/components/radio/radio.py
- mesop/components/radio/radio.scss
- mesop/components/radio/radio.ts
- mesop/examples/__init__.py
- mesop/examples/checkbox_and_radio.py
- Changes default label position to "after" which is what [Angular Material defaults](https://github.com/angular/components/blob/4719da2c34bee87095a2368334715e415f18a4c3/src/material/radio/radio.ts#L121) to and what checkbox currently defaults to.
- Sets the display type to `block` as this is the most common behavior.
I will open a separate PR so that radio (& other components) can be styled, so Mesop app developers can override this.
> Update default UI for radio component

- mesop/examples/e2e/chat_test.ts
Not sure if there's a better way but I noticed it's been flaky.
Example: https://github.com/google/mesop/actions/runs/8795330360?pr=135
> Increase timeout in chat_test due to flakiness

- mesop/cli/cli.py
Closes #47 
This fixes two related issues:
- Previously, if you went to page "/" and there was an error hot reloading (i.e. in `execute_main_module`) you would wait for  [wait_for_hot_reload](https://github.com/google/mesop/blob/f176cce48515552914df1a124ced0bc1a183e049/mesop/runtime/runtime.py#L64) before seeing the error. Now, you will see the error message right away.
- Catches error message and displays it in UI ([similar](https://github.com/google/mesop/blob/f176cce48515552914df1a124ced0bc1a183e049/mesop/cli/cli.py#L72) to the first time execute module)
> Improve DevEx for hot reloading: show errors from hot reloading right away

- mesop/examples/e2e/chat_test.ts
- mesop/examples/testing/__init__.py
- mesop/examples/testing/minimal_chat.py
Changes:
- Creates a minimal chat app with no sleep to speed up the test
- Skips assertions on the in-progress state 'Processing prompt...' - this seems inherently flaky because it's possible to miss it (if it happens too quickly now that there's no sleep)
This test isn't quite as high fidelity as before (but still covers most of the functionality) but it greatly alleviates the flakiness.
Checked (passed 10/10 times):
```sh
$ yarn playwright test  mesop/examples/e2e/chat_test.ts --repeat-each=10
```
> Deflakes chat_test.ts

- mesop/examples/buttons.py
- mesop/web/src/app/styles.scss
Docs: https://material.angular.io/guide/material-3#optional-add-backwards-compatibility-styles-for-color-variants
I missed this earlier so color variants like `me.button("hi", color="warn")` were not working.
- Drive-by: remove dark theme which is unused right now.
Fixes #149
> Fix angular material colors for M3

- build_defs/app_bundle/BUILD
- build_defs/app_bundle/README.md
- build_defs/app_bundle/esbuild.config-tmpl.mjs
- build_defs/app_bundle/index.bzl
- build_defs/app_bundle/terser_config.json
- build_defs/defaults.bzl
- build_defs/ng_js_binary.bzl
- mesop/web/src/app/BUILD
- mesop/web/src/app/prod/BUILD
- mesop/web/src/app/prod/index.html
- package.json
- yarn.lock
Fixes #61.
TLDR: compiling Angular app with Bazel is painful, especially with protos.
Previously, even in prod mode, the Mesop app was compiled in Angular dev mode, which is not ideal, particularly for performance reasons (Angular prod mode is AOT compiled instead of dev mode which is JIT compiled).
Because there isn't a well-lit path for compiling Angular apps in Bazel, we end up copying what tensorboard has done: https://github.com/tensorflow/tensorboard/blob/4023658707d54976622c3b3a32f5a4a215689da7/tensorboard/defs/defs.bzl#L93 which is essentially to use Angular internal build toolchain for OSS.
However, we couldn't use Angular's internal `app_bundle` Bazel def directly because Mesop needs a custom esbuild plugin to resolve the generated JS paths for protos, so we ended up forking …
> Create optimized / prod-Angular app for prod mode

- .github/workflows/ci.yml
- mesop/component_helpers/BUILD
- mesop/component_helpers/__init__.py
- mesop/component_helpers/diff_component_test.py
- mesop/component_helpers/helper.py
- mesop/examples/testing/__init__.py
- mesop/examples/testing/complex_layout.py
- mesop/protos/ui.proto
- mesop/runtime/context.py
- mesop/server/BUILD
- mesop/server/server.py
- mesop/tests/e2e/diff_test.ts
- mesop/web/src/services/channel.ts
- mesop/web/src/utils/BUILD
- mesop/web/src/utils/diff.ts
- mesop/web/src/utils/diff_spec.ts
- playwright.config.ts
This change is gated by a flag called `enable_component_tree_diffs`. When enabled, the full component tree will not be returned in event responses. Instead only the changed component fields will be returned to the frontend. The frontend will then apply the diff to update its copy of the component tree.
A few notes:
- Wasn't sure how to add unit tests for typescript. Is there a framework we're using?
- I'd like to run the playwright tests with the diff flag enabled and without it enabled (right now it's enabled by default in the test). Haven't looked into this too much yet. Seems like there's a way to do it 
- Passing in a different config but that would lead to a lot of duplication (so probably rule this out)
- Seems like we could pass in some environment variable to enable/disable the …
> Add component diffing on event responses.

- mesop/bin/bin.py
- mesop/cli/cli.py
- mesop/cli/dev_cli.py
- mesop/cli/execute_module.py
- mesop/pip_package/requirements.txt
Closes #150.
Note: this doesn't work with Python relative imports which seems relatively less popular than Python absolute imports.
> Use watchdog for a more robust file watching for mesop/bin

- mesop/cli/cli.py
- mesop/cli/dev_cli.py
- mesop/server/colab_run.py
- mesop/server/server.py
- mesop/server/wsgi_app.py
Closes #175 
Component configs is only needed for editor mode.
> Don't send component configs in prod mode

- mesop/runtime/context.py
- mesop/server/server.py
Hot reloading was not working with component diffs since the diffs were returning no changes.
This is because the render loop does not have access to the old tree before hot reloading. Since that tree does get sent with the event, it's possible we could update the code to use the old tree, but for development, it seems ok to just perform a full diff.
There is also the use case of pressing the back button, which triggers a UI event. This event does not provid a handler ID so it will now a skip diffing.
Also the `reset_nodes` method was removed. With this change, the naming became a bit confusing. So ended up just explicitly calling each method.
> Fix bug with hot reload and component diffs

- mesop/examples/__init__.py
- mesop/examples/llm_rewriter.py
This extends the chatbot example to include the ability to rewrite LLM responses.
I'm not too familiar with is needed for an LLM rewriter. But here's my initial attempt. Initially planning to do a side by side preview like in some of the screenshots I saw.
But I felt like a modal was slightly better since it's a bit tougher to make the side by side work well in a responsive fashion. But also a modal is a common UI use case (I'll probably spin off a separate modal example).
- Edit icon
- Click bot response to edit
- Modal with rewrite UI
- Side by side comparison of original message and rewritten message
- Markdown preview edits
- Updated message bubble contains indicators that its edited
- Chat bubble turns purple
- "(edited)" is appended to the bot name
> Add LLM Rewriter example.

- mesop/web/src/shell/shell.ng.html
- mesop/web/src/shell/shell.ts
Closes #201.
The previous behavior was overly complicated in trying to show multiple errors, but it resulted in an annoying developer experience where you needed to manually close the red error box (or reload the page) once you fixed the error.
In the vast majority of cases, you're dealing with one error at a time, and if you really have multiple errors at once (e.g. JS errors), then you can still debug them one at a time with the error box still
> Do not show error box once error is no longer current

- mesop/editor/component_configs_test.py
- mesop/editor/editor_codemod_test.py
- mesop/editor/testdata/delete_custom_component/after.py
- mesop/editor/testdata/delete_custom_component/before.py
- mesop/editor/testdata/new_custom_component/after.py
- mesop/editor/testdata/new_custom_component/before.py
- mesop/editor/testdata/update_columns/after.py
- mesop/editor/testdata/update_columns/before.py
- mesop/examples/__init__.py
- mesop/examples/columns.py
- mesop/examples/index.py
- mesop/labs/layout.py
This was an experimentation from a while back but I don't think this is the right way to support columns because it's usually not what people expect. This basically splits a big body of text across multiple columns, but usually I think people want a grid-like layout (even a single row) where each column is a body of text.
> Remove columns from mesop.labs.layout

- build_defs/defaults.bzl
- build_defs/requirements.txt
- build_defs/requirements_lock.txt
- mesop/components/markdown/BUILD
- mesop/components/markdown/e2e/markdown_app.py
- mesop/components/markdown/markdown.ng.html
- mesop/components/markdown/markdown.proto
- mesop/components/markdown/markdown.py
- mesop/components/markdown/markdown.ts
- mesop/pip_package/requirements.txt
- mesop/web/src/app/styles.scss
Instead of doing the markdown rendering client-side using [marked.js](https://marked.js.org/), this changes our markdown component's implementation to instead do it on the server-side using [python-markdown](https://python-markdown.github.io/) for markdown rendering and [pygments](https://pygments.org/) for syntax highlighting.
Shifting it to server-side seems better because: 1) it ships less code to client-side which is more performant and 2) most of the heavy-lifting in Mesop apps is done on the server-side already so there wasn't much benefit to doing it client side.
Addresses part of #96.
> Supports syntax highlighting in markdown (uses python-markdown + pygments)

- docs/internal/hot_reload.md
- mesop/cli/BUILD
- mesop/cli/cli.py
- mesop/runtime/runtime.py
- mesop/server/server.py
- mesop/web/src/editor/editor.ts
- mesop/web/src/services/channel.ts
- mesop/web/src/services/hot_reload_watcher.ts
This PR has two goals:
1. Fix the DevEx issues described in #199.
2. Unify the hot reload mechanism between `ibazel` and `mesop` CLI. This way if we break one, particularly for the `mesop` CLI, we will feel the pain right away as framework developers.
This creates a new HTTP endpoint "/hot-reload" that the Mesop client app long polls against. If "/hot-reload" returns a 200 (OK) HTTP response this means the Mesop server has finished re-executing the changed modules, then the Mesop client app triggers a hot reload request.
As a nice side-effect, this avoids the ibazel livereload mechanism which is somewhat hairy and relies on this pre-compiled [JS file](https://github.com/jaschaephraim/lrserver/blob/afed386b3640edd11a398a686f178a810530c990/livereload_v4.0.2/livereload.js).
Fixes #199.
Note: …
> Replace hot reload mechanism

- mesop/server/wsgi_app.py
This fixes two related issues fixed with our `wsgi_app` implementation:
- Previously, there was no flag parsing (for absl-py) when running Mesop via gunicorn (recommended for production serving) which resulted in a [UnparsedFlagAccessError](https://abseil.io/docs/python/guides/flags#how-do-i-fix-unparsedflagaccesserror), because of this flag: https://github.com/google/mesop/blob/8ccc8d234f33d675fe3018c10817be917ee3a1a7/mesop/runtime/context.py#L15C1-L16C1. This uses the manual flag parsing method, instead of the usual `app.run` because `app.run` never returns, so we can't use it here.
- Previously, we were creating a new Flask app instance for each request, which technically works, but it's wasteful since a Flask app is supposed to be persistent. This saves ~5ish ms per request by caching …
> Fix `wsgi_app` - flag parsing & singleton

- mesop/runtime/runtime.py
- mesop/server/server.py
- mesop/web/src/services/channel.ts
Fixes #200. 
The problem before this was that if there were multiple clients (e.g. multiple tabs, multiple frames) connected to the same Mesop development server, then only one of the client would be properly signaled to do a hot reload because Runtime is a singleton and `hot_reload_ready_for_client` was set to True as soon as one client was signaled to do a hot reload request.
This makes the hot reload watching protocol more robust by having the client send its current hot reload count and comparing whether the server has a higher count.
Note: if the client misses a hot reload event (e.g. the count is off by more than 1), it's not a big deal because the client will effectively just catch up to the latest.
> Make hot reloading work with multiple clients

- mesop/runtime/runtime.py
Fixes #216.
This changes it from a `MesopUserException` to a `MesopDeveloperException` because it's not really a user issue if there's no pages registered at all.
> Show a more informative error message if no page registered

- mesop/exceptions/__init__.py
- mesop/server/server.py
Avoid leaking internal implementation details to end-users.
Note: MesopUserExceptions and general exceptions are still shown to the user.
> Redact internal & developer error messages in prod mode

- mesop/bin/bin.py
Accidentally left it in https://github.com/google/mesop/commit/03ebcc5b4cd4cf301b84311b8601ea1ea1d8f588
> Remove unnecessary detail (event) from hot reload print

- demo/main.py
- demo/markdown_editor.py
While working on the LLM Rewriter, it occurred to me it would be pretty easy to make a markdown editor using Mesop. Thought it would make a decent example in the vein of the typical todo list type example.
> Add markdown editor example

- demo/llm_playground.py
- demo/main.py
Here's the LLM Playground example. I based it roughly off of the GCP Vertex AI UI (only added some of the fields they had). I also looked briefly at the Chat GPT one.
> Add LLM Playground example

- mesop/labs/chat.py
I find it somewhat hard to read the chat text - WDYT about adjusting it higher? (We could also make it configurable via a parameter, but generally I think chat UIs are around this font size).
**Before:**
**After:**
> Make labs.chat text easier to read

- mesop/web/src/dev_tools/dev_tools.scss
- mesop/web/src/editor/editor.ng.html
- mesop/web/src/editor/editor.scss
Fixes #244.
- Removes the slight border around the app content when developing in editor mode. Instead, we put a border on the devtools panel itself to provide visual distinction.
- This fixes an unrelated issue in the same area where you can accidentally resize devtools even when devtools isn't open, which creates a funky situation. I originally wanted the resizer there in case people resize devtools to be too small, but in that case you can always reload the page and you'll see the devtools at the default width.
> Polish the editor/devtools UX

- mesop/server/BUILD
- mesop/server/static_file_serving.py
- mesop/server/static_file_serving_test.py
- Fixes #231 
- This produces a significant size savings, particularly for the JS bundle (~4x: 1.6MB -> 400kb for prod mode).
- Although ideally gzipping is handled outside of the Flask server and at another layer (e.g. a web server like NGINX),  there's benefits to doing it in the Flask app because in development use case, particularly with Colab, it can be quite slow to load the JS bundle.
- To avoid paying the cost of gzipping the same files over and over again (~30ms on my local computer), this implements a singleton cache. This is OK assuming that the file contents of what we're caching do not change (for these static files, this should hold true).
> Implement gzipping for static file serving

- .pre-commit-config.yaml
- mesop/server/static_file_serving.py
- mesop/tests/e2e/snapshots/web_security_test.ts_csp.txt
- mesop/tests/e2e/web_security_test.ts
- mesop/web/src/app/dev/index.html
- mesop/web/src/app/editor/index.html
- mesop/web/src/app/prod/index.html
- playwright.config.ts
Fixes #225. I opened up #271 because it's the remaining major web security piece we should shore up.
Notes:
- CSP is quite easy to mess up due to weird syntax it uses, so I've done a snapshot test to avoid accidental regressions.
- Using CSP nonce requires us to generate a random string and set it on the server ([ref](https://angular.io/guide/security#content-security-policy:~:text=Set%20the%20ngCspNonce%20attribute%20on%20the%20root%20application%20element%20as%20%3Capp%20ngCspNonce%3D%22randomNonceGoesHere%22%3E%3C/app%3E.%20Use%20this%20approach%20if%20you%20have%20access%20to%20server%2Dside%20templating%20that%20can%20add%20the%20nonce%20both%20to%20the%20header%20and%20the%20index.html%20when%20constructing%20the%20response.))
> Setup reasonable default web security policies

- mesop/server/server.py
- mesop/web/src/shell/shell.ts
Fixes #269.
The previous implementation was naive - sending down all the component configs with every render event which is wasteful and eats >300ms. We can use the component configs from the first render.
The only downside to this change is that if the user adds a new component (e.g. using `@me.component`) it won't send down the new component config, but this isn't that big of a deal because 1) the component will work, it just won't show up in the right-hand devtools/editor panel, and 2) the developer can refresh the page (triggering all the component configs to be resent).
> Stop sending component configs with every render event in Editor mode

- demo/llm_playground.py
The click event will be triggered on the nested elements, so this prevents copy and pasting of the code.
For now just using a click event on the close button.
Also logged an issue here: https://github.com/google/mesop/issues/268
> Remove click event on modal bg for LLM Playground.

- mesop/cli/cli.py
- mesop/server/static_file_serving.py
- mesop/server/static_file_serving_test.py
#261 inadvertently made developing Mesop Angular components painful because the gzip cache would make client-side changes force a server restart in order to observe the changes.
> Disable gzip in cache in editor mode to make component development easier

- mesop/server/static_file_serving.py
This only seems to be needed downstream because we render markdown by setting it to innerHTML which calls https://github.com/angular/angular/blob/f7894885b80dbdca99877569ea98aac2dc175e6c/packages/core/src/sanitization/sanitization.ts#L47
It's unclear how this was working earlier in OSS because even when you use the HTML sanitizer it still relies internally on the bypass APIs
> Add angular#unsafe-bypass to CSP

- mesop/tests/e2e/web_security_test.ts
The nonce could sometimes contain non-word character like _ which made it flake because the previous RegEx wouldn't capture the entire nonce string
> Deflake web_security_test

- demo/basic_animation.py
- mesop/component_helpers/style.py
- mesop/editor/component_configs.py
- mesop/protos/ui.proto
- mesop/web/src/utils/styles.ts
New properties
- visibility
- opacity
- top / left / right / bottom
- Add remaining grid properties:
- grid_auto_columns
- grid_auto_flow
- grid_auto_rows
- grid_column
- grid_row
- Exception: left out grid_template property
Also some minor style property fixes
- Allow string values for:
- grid_column_start
- grid_column_end
- grid_row_start
- grid_row_end
- Fix potential bug with direct str conversions
- If the value is not set, setting str(property) would yield 'None'
- That seems undesirable, so add _int_str and _float_str wrappers
- Fixes #298 
- Fixes #281 
- Fixes #280 
- Fixes #266
> Add some new style properties to the Style class

- demo/slider.py
- mesop/components/slider/e2e/slider_app.py
- mesop/components/slider/e2e/slider_test.ts
- mesop/components/slider/slider.ng.html
- mesop/components/slider/slider.proto
- mesop/components/slider/slider.py
- mesop/components/slider/slider.ts
This change allows the value to be set for the slider. The implemented behavior here is similar to the input/textarea value field.
The value will update the value of the slider only if the value being passed in changes.
This is for the following use cases:
1. Setting an initial value
2. Updating the value programmatically. For example if you wanted a textbox to control the slider value
3. Only updating the value if it changes, allows the slider to move smoothly (same issue as the text inputs)
Fixes #241
> Allow user to set value for slider.

- demo/basic_animation.py
- mesop/component_helpers/style.py
- mesop/protos/ui.proto
- mesop/web/src/utils/styles.ts
Properties added:
- rotate
- transform
- justify_self
- align_self
One thing to note here is that I noticed justify_self/justify_items and align_self/align_items do not have the exact same property values. Also there were some property values missing from the ItemAlignmentValues Literal definition. I ended up adding the missing values and creating a separate Literal definition for justify_self/justify_items. I believe this should be ok since it's just a Literal definition, so API should be the same still.
Also added some animation examples using rotate and transform.
- Fixes #302
- Fixes #303
> Add some new style properties

- mesop/__init__.py
- mesop/components/input/e2e/input_app.py
- mesop/components/input/e2e/input_test.ts
- mesop/components/input/input.ng.html
- mesop/components/input/input.proto
- mesop/components/input/input.py
- mesop/components/input/input.ts
Add an `on_enter` handler for `<input type="text">` type components, so that input boxes can be "submitted" using the keyboard. Currently, there's no handler for "Enter", so input boxes are usually "submitted" using a relevant button hooked to a handler.
> Add an on_enter handler for input type components

- mesop/cli/BUILD
- scripts/cli.sh
Fixes #289.
By removing the prod dependency (JS binary) it makes the edit/refresh cycle much faster for client-side changes.
> Create an editor_cli target to make edit/refresh cycle faster

- mesop/server/server.py
When deploying on Google Cloud Run - the origin is https, however the url root is http, so that's why was it failing the is same origin check.
Related to #310
> Check is same site instead of same origin for CSRF check

- .devcontainer/devcontainer.json
- Dockerfile
- docker-compose.yml
- scripts/devcontainer_setup.sh
- This change allows one click installation with Github Codespaces
- Using the default resources, it does take a long time to install
- This change also allows remote container dev in VSCode
- Running ibazel in the container is  a bit slow
- Does not support Linux ARM yet. See #361
- Also can't push commits unless ssh keys are set up
- Need to see if there is a better way to do that
- Will add docs later
- Probably still need to work out various kinks
Ref #101
> Add devcontainer support for Mesop dev.

- generator/utils.py
- generator/utils.ts
Modified the `capitalize_first_letter` function to utilize Python's built-in `str.capitalize` method. Here's a detailed explanation of the changes:
```python
def capitalize_first_letter(s: str) -> str:
if not s:
return s
return s[0].upper() + s[1:]
```
1. **Check for Empty String**: The function first checks if the input string `s` is empty. If it is, the function returns the empty string.
2. **Manual Capitalization**: If the string is not empty, the function manually capitalizes the first character by converting `s[0]` to uppercase and then concatenating it with the rest of the string (`s[1:]`).
```python
def capitalize_first_letter(s: str) -> str:
if not s:
return s
return s.capitalize()
```
1. **Check for Empty String**: The function retains the check for an empty string and returns it …
> modified the capitalize_first_letter function

- mesop/web/src/services/channel.ts
- mesop/web/src/shell/shell.ts
> Only show channel progress indicator if it's taking >500ms to avoid jarring UX

- mesop/server/server.py
**Consolidation of Initial Checks:**
The checks for whether `url1` or `url2` is `None` have been combined into a single line.
> Update is same site

- mesop/examples/__init__.py
- mesop/examples/custom_font.py
- mesop/features/page.py
- mesop/runtime/runtime.py
- mesop/server/static_file_serving.py
- mesop/web/src/app/editor/index.html
- mesop/web/src/app/prod/index.html
Early on, I hardcoded several Google-specific fonts for a demo, and this basically unwinds some of the tech debt as it's just extra bloat for most Mesop apps, particularly externally.
Downstream, I'll need to set a default_stylesheets value for these Google-specific fonts to avoid affecting current Mesop apps in Google.
Fixes #364
> Configure custom fonts/stylesheets instead of hardcoding

- demo/main.py
Otherwise, there's an error because the demo gallery runs in an iframe and the GitHub repo page prohibits being iframed.
> Demo gallery: open github link in new tab/window

- demo/html_demo.py
- demo/main.py
- docs/components/html.md
- mesop/BUILD
- mesop/__init__.py
- mesop/components/html/BUILD
- mesop/components/html/e2e/BUILD
- mesop/components/html/e2e/__init__.py
- mesop/components/html/e2e/html_app.py
- mesop/components/html/e2e/html_test.ts
- mesop/components/html/html.ng.html
- mesop/components/html/html.proto
- mesop/components/html/html.py
- mesop/components/html/html.ts
- mesop/example_index.py
- mesop/examples/BUILD
- mesop/web/src/component_renderer/BUILD
- mesop/web/src/component_renderer/type_to_component.ts
- mkdocs.yml
This allows you to render sanitized HTML, however it doesn't allow potentially dangerous HTML like JavaScript.
In a separate PR, I'll update the `embed` component so you can essentially do an `<iframe srcdoc="$htmlcontent">`, which will allow you to run arbitrary JS in a sandboxed way.
Partially addresses #156.
> Add `html` component

- mesop/web/src/component_renderer/component_renderer.ts
I was mistakened in #416 where I actually need to use dot property access so that downstream the property name is consistently renamed across files in the main JS binary. The web components do not actually access the property names for MesopEvent so we don't need to worry about syncing the property names there.
> Fix property access for MesopEvent

- Dockerfile
This is related to #445
Apparently postCreateCommand is run the container user specified in the image, which for us is mesop-dev.
Unfortunately to install some additional software and configure access to node modules, we need root access via sudo.
A few things this will help us with:
1) Allow us to update the ownership of the node_modules directory to mesop-dev. This is because it is created as a Docker volume via Docker compose and ownership will be root. Need to verify if this is working correctly. Github Codespaces behavior seems a bit different.
2) Allows us to remove some of the Playwright installation dependencies out of the Docker image. With sudo we can install the additional browser dependencies via the yarn playwright "install-deps" command instead if we needed to. The nice …
> Add sudo support inside Docker image.

- mesop/components/select/e2e/__init__.py
- mesop/components/select/e2e/select_app_multiple.py
- mesop/components/select/e2e/select_test.ts
- mesop/components/select/select.ng.html
- mesop/components/select/select.proto
- mesop/components/select/select.py
- mesop/components/select/select.ts
> Allow multiple selections on select box

- docs/index.md
The link to components is broken.
It should be `./components` instead of `./guides/components`
> chore: fix typo in docs/index.md

- build_defs/requirements.txt
- mesop/pip_package/requirements.txt
Does not look like there any breaking changes: https://zepworks.com/deepdiff/current/changelog.html
Ref #468
> Unpin deepdiff

- package.json
- yarn.lock
Ref: https://github.com/google/mesop/issues/361
This upgrade is needed to support Mesop builds of ARM on Linux. This includes running Linux on Docker images on MacOS.
There are various warnings that show up when running ./scripts/cli.sh
It's unclear to me if these are OK to ignore not. It's also unclear which package some of these errors are coming. I think some may be comming from "google-protobuf" library. I guess there was recently a patch version update to 3.21.3 (we have 3.21.2) but that is not released yet.
On the Linux builds, we get a various warnings like this:
```
external/com_google_protobuf_javascript/generator/js_generator.cc: In member function 'bool google::protobuf::compiler::js::GeneratorOptions::ParseFromOptions(const …
```
> Update grpc-tools to 1.12.4

- docs/blog/posts/why_mesop.md
similar to #487
The link to components is broken.
It should be `./components` instead of `./guides/components`
> chore: fix typo in posts/why_mesop.md

- demo/input.py
- demo/textarea.py
- docs/components/input.md
- docs/components/textarea.md
- mesop/__init__.py
- mesop/components/input/e2e/__init__.py
- mesop/components/input/e2e/input_blur_app.py
- mesop/components/input/e2e/input_test.ts
- mesop/components/input/input.ng.html
- mesop/components/input/input.proto
- mesop/components/input/input.py
- mesop/components/input/input.ts
Fixes #516.
This allows people to avoid using `on_input` in the common case.
> Add `on_blur` for input / textarea

- docs/api/page.md
- docs/guides/web_security.md
- mesop/security/security_policy.py
- Fixes indentation in security_policy.py because mkdocs complained
> Add SecurityPolicy to docs

- README.md
- demo/README.md
- docs/getting_started/installing.md
- docs/guides/deployment.md
- docs/index.md
- docs/internal/development.md
- docs/internal/modes.md
- docs/internal/new_component.md
- docs/internal/publishing.md
- docs/internal/testing.md
- docs/internal/type_checking.md
- mesop/examples/web_component/firebase_auth/README.md
Since mkdocs for material doesn't strip out the $ when copying the code, it's annoying to have the prefix.
See: #430.
> Remove $ prefix from shell commands

- docs/guides/deployment.md
Reorganizes the docs to include Cloud Run, App Engine, and Docker configurations.
> Update deployment docs

- docs/internal/codespaces.md
The absolute URL does not work since the url path get displayed as a sub directory when published live.
The fix is to use relative images URLs instead.
Ref #539 
Ref https://github.com/google/mesop/issues/101
> Fix broken images Github Codespaces

- mesop/colab/colab_run.py
- mesop/runtime/context.py
- mesop/server/wsgi_app.py
This feature has been enabled for long enough that we feel comfortable with removing the option to disable this behavior.
Ref #62
> Remove `enable_component_tree_diffs` flag

- docs/internal/vs_code_remote_container.md
Adds instructions for using git credentials in the remote container for VS Code remote container development.
ref #101
> Update VS Code Remote container doc

- demo/markdown_demo.py
- mesop/components/markdown/e2e/markdown_app.py
- mesop/components/markdown/e2e/markdown_test.ts
- mesop/components/markdown/markdown.py
- mesop/web/src/app/styles.scss
This change allows markdown tables to be rendered correctly. One caveat is that custom styling is not possible unless someone includes an custom stylesheet via CDN or external URL.
This means that the default rendering is very basic.
If a user wants to use render markdown from a pandas data frame, they will need to install tabulate separately.
Attribute lists have also been enabled to make it easier to style the the tables via CSS.
[
](url)
Ref #546
> Enable markdown tables + attribute lists

- demo/uploader.py
- mesop/components/uploader/uploader.ng.html
- mesop/components/uploader/uploader.proto
- mesop/components/uploader/uploader.py
- mesop/components/uploader/uploader.ts
To make the experience more consistent, this change copies the same parameters from button to uploader. This will allow users to customize the button colors / type / style and disable it.
Ref #568
> Add button attributes to uploader

- build_defs/defaults.bzl
- build_defs/requirements.txt
- build_defs/requirements_lock.txt
- docs/api/config.md
- mesop/pip_package/requirements.txt
- mesop/server/BUILD
- mesop/server/config.py
- mesop/server/config_test.py
- mesop/server/state_session.py
- mesop/server/state_session_test.py
This change also adds a new dependency with msgpack. For now we use it to serialize/deserialize the JSON strings of the Mesop state. In the future we will want to serialize everything with msgpack.
The reason we can't do this now is because we will need to add msgpack encoding/decoding rules to support non-standard data types.
This change also adds a new config variable called MESOP_STATE_SESSION_BACKEND_FILE_BASE_DIR which allows the user to specify the location where the state sessions get written.
Ref #556
> Add file backend for state sessions

- demo/grid_table.py
- demo/main.py
One thing I'm beginning to notice is that some of the Angular Components aren't really that special. And that we can probably write pure Mesop versions that would be more amenable to the Mesop event flow.
So one thing that occurred to me is that we don't need to render tables using table mark up. We can just use flex box or grid. In this case I used grid.
By doing this, it allows us to implement more advanced functionality quicker than if we to work with the Angular Table component. And I know some people have been asking for more table functionality.
So as an example, I tried to build a a moderately featured table component. One major thing that is missing is pagination, but I ran out of gas. But otherwise we have custom styling, flexible custom cell formatting, sorting, filtering. …
> Add grid table demo

- docs/api/config.md
- mesop/server/BUILD
- mesop/server/config.py
- mesop/server/config_test.py
- mesop/server/state_session.py
- mesop/server/state_session_test.py
- Adds `firestore` option to `MESOP_STATE_SESSION_BACKEND`
- New config: `MESOP_STATE_SESSION_BACKEND_FIRESTORE_COLLECTION`
- Updates config.md
- Notes on implementation
- User needs to manually set the TTL policy - Though the policy seems a bit slow to delete stuff
- Uses the `(default)` database only
- Uses application default credentials to pick project
Ref #556
> Add Firestore state session backend

- mesop/components/input/input.ng.html
- mesop/components/input/input.ts
The isComposing field tells us if we are using an input method editor (IME) which
will display a menu of characters that can't be represented on a standard QWERTY
keyboard. The user can select from this menu by pressing "enter" or clicking the
menu item. The user will then need to press "enter" to confirm the selection (at
least on MacOS).
If we do not check isComposing on key up, this will trigger the Mesop on enter
event.
If we check isComposing on key up, the enter confirmation will trigger the Mesop
on enter event since isComposing becomes false on key up.
We need to track isComposing with the key down event since this will trigger the
on enter event when "enter" is pressed again (when the IME is inactive and
a selection has been made and applied).
Safari has a bug where the order of …
> Fix false on enter trigger when using IME.

- docs/components/code.md
- docs/components/html.md
- docs/components/select.md
- Fix select to select_demo
- Fix code to code_demo
- The html one does not have a live demo yet since the demo gallery is at v0.8.0
Ref: https://github.com/google/mesop/issues/596
> Fix broken iframe links in docs

- mesop/server/config.py
For some reason the default `load_dotenv()` behavior is not working as expected for pip installs. To fix this, we update the code to explicitly search the user's current working directory.
This does not work when running in Bazel, so we still need to use `load_dotenv()`.
Tested this by running ./scripts/pip.sh and also testing ./scripts/cli.sh.
Ref: https://github.com/google/mesop/issues/592
> Fix bug with .env not loading for pip installs

- docs/blog/posts/web_components.md
@richard-to WDYT? :) I'm thinking about publishing this blog post and sharing it on social media 😃
> Create python FE fatigue blog post

- mesop/tests/e2e/web_components/slot_test.ts
- playwright.config.ts
- Removed retries for the overall test suites because it can mask real issues and we can mark specific tests as flaky, such as web component slot test which is flaky both locally and on GitHub.
> Budget more time for playwright tests & disable retries

- mesop/colab/colab_run.py
- mesop/colab/colab_run_test.py
- mesop/colab/colab_show.py
- mesop/colab/colab_utils.py
> Add notebook_show, notebook_run for Jupyter notebook environments

- docs/codelab/2.md
- docs/codelab/3.md
- docs/codelab/4.md
- docs/codelab/5.md
- docs/codelab/index.md
- docs/getting_started/installing.md
- mkdocs.yml
Code repo: https://github.com/wwwillchen/mesop-duo-chat
Demo: https://huggingface.co/spaces/wwwillchen/mesop-duo-chat
> Create DuoChat codelab

- mesop/server/static_file_serving.py
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-allowed-iframe-parents.txt
- mesop/tests/e2e/snapshots/web_security_test.ts_csp.txt
Closes #628.
`frame-src` (i.e. iframing other sites) is fairly low-risk and we may as well allow iframing any site. This is different than `frame-ancestors` which is much more security sensitive and has a strict allowlist.
Background: https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html#preventing-framing-attacks-clickjacking-cross-site-leaks
> Allow iframing any other sites

- mesop/examples/BUILD
- mesop/examples/__init__.py
- mesop/examples/starter_kit/BUILD
- mesop/examples/starter_kit/__init__.py
- mesop/examples/starter_kit/starter_kit.py
- Creates a chat-like UI as a starter template which demonstrates core Mesop functionality , particularly with styling.
- Will be followed up by creating a `mesop init` CLI command.
> Create starter kit template

- docs/components/index.md
- docs/getting_started/core_concepts.md
- docs/getting_started/installing.md
- docs/getting_started/quickstart.md
- docs/guides/interactivity.md
- docs/guides/multi_pages.md
- docs/stylesheets/extra.css
- mkdocs.yml
@richard-to do you think there should be a standalone docs page for the starter kit?
> Update docs with starter kit

- mesop/runtime/context.py
- mesop/runtime/runtime.py
- It's better to do the type annotations inside `__init__` instead of annotating at the class variable.
- Initializing class variables is sketchy, particularly with mutable objects.
- We were previously initializing class variables to mutable values on Runtime, which is technically not too bad because Runtime is a singleton object, but this is still a bad practice.
> Do not use class variables in runtime modules

- docs/guides/state_management.md
- docs/stylesheets/extra.css
I think the docs before were not vocal enough about avoiding this pitfall. I'm also exploring a way of programmatically safe-guarding against mutable default values, but it's a bit tricky - see #647.
> Provide more explicit docs about mutable state default values

- demo/table.py
- mesop/bin/bin.py
- mesop/components/table/e2e/table_app.py
- mesop/server/state_session_test.py
- mesop/utils/path_utils.py
- pyproject.toml
https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
In particular, it contains https://docs.astral.sh/ruff/rules/mutable-class-default/ which would catch the issue that was fixed in #642.
> Enable RUF lint rules

- .github/workflows/ci.yml
- mesop/examples/__init__.py
- mesop/examples/concurrency_state.py
- mesop/tests/e2e/concurrency/state_test.ts
Fixes #654.
This test has its own GitHub Actions workflow step because I couldn't figure out a way to force a high number of workers for a specific test using playwright's config.
> Create a concurrency test to stress-test state is isolated across sessions

- demo/headers.py
- demo/main.py
A common use case to have a header for the app. This example was extracted from the prompt tuner console app that I've been working on.
Also think it will be useful for the Mesop AI stuff.
Ref: https://github.com/google/mesop/issues/338
> Add example headers to patterns demos.

- .pre-commit-config.yaml
- mesop/dataclass_utils/dataclass_utils.py
- mesop/dataclass_utils/dataclass_utils_test.py
Fixes #644.
Note: this will raise an exception if someone tries to use a proto type in a state class. Before this, we weren't throwing an exception but we were silently not properly serializing & deserializing the proto state (effectively not updating the proto). We'll need to call this out when we sync downstream, and maybe we should support protos properly, but this is at least more explicit.
> Catch accidental usages of mutable default state values

- demo/dialog.py
- demo/markdown_demo.py
Also minor adjustment for dialog box actions. Add a small flex gap.
Apparently with the markdown module we're using, you need four spaces for the nested lists to trigger. So updated markdown demo to reflect.
> Fix markdown indention in markdown demo

- mesop/examples/custom_font.py
- mesop/examples/web_component/BUILD
- mesop/examples/web_component/__init__.py
- mesop/examples/web_component/custom_font_csp_repro/BUILD
- mesop/examples/web_component/custom_font_csp_repro/counter_component.js
- mesop/examples/web_component/custom_font_csp_repro/counter_component.py
- mesop/examples/web_component/custom_font_csp_repro/custom_font_app.py
- mesop/server/static_file_serving.py
- mesop/tests/e2e/web_components/custom_font_csp_test.ts
- mesop/utils/BUILD
- mesop/utils/url_utils.py
- mesop/utils/url_utils_test.py
Received a report that Mesop apps are having misconfigured CSP caused by stylesheet URLs.
I've removed query params because: 1) the query component is ignored (see error message below from Chrome) and 2) it can contain separator characters ";" and "," which was causing the CSP to break. As a follow-up, we can escape or raise an exception if any of the CSP inputs contains one of these separator characters.
```
The source list for Content Security Policy directive 'style-src' contains a source with an invalid path: '/css2?family=Tiny5&display=swap'. The query component, including the '?', will be ignored.
```
This also addresses the issue in #549.
> Remove query params from stylesheet URLs when adding it to CSP

- mesop/examples/testing/__init__.py
- mesop/examples/testing/csp_escaping.py
- mesop/server/static_file_serving.py
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-escaping.txt
- mesop/tests/e2e/web_security_test.ts
- mesop/utils/url_utils.py
- mesop/utils/url_utils_test.py
This prevents values from accidentally (or potentially intentionally) breaking the CSP syntax.
> Escape CSP source values

- mesop/examples/testing/__init__.py
- mesop/examples/testing/error_register_page_too_late.py
- mesop/examples/testing/error_register_web_component_too_late.py
- mesop/runtime/runtime.py
- mesop/tests/e2e/late_registration_error_test.ts
We want to avoid an anti-pattern where Mesop app developers are defining a page or web component dynamically after _any_ traffic has been served (page and web components are registered globally as part of the runtime singleton, and are not scoped to a specific context/request). 
For example, we want to prevent the following:
```py
@me.page()
def p():
s = me.state(State)
@me.page(security_policy=me.SecurityPolicy(allowed_frame_parents=[s.user_input]))
def dynamic_page():
pass
```
> Prevent page or web component from being registered after traffic has been served

- mesop/examples/web_component/BUILD
- mesop/examples/web_component/__init__.py
- mesop/examples/web_component/markedjs/BUILD
- mesop/examples/web_component/markedjs/markedjs_app.py
- mesop/examples/web_component/markedjs/markedjs_component.js
- mesop/examples/web_component/markedjs/markedjs_component.py
- mesop/server/static_file_serving.py
This component uses MarkedJS for markdown, Mermaid for diagrams, and HighlightJS for code highlighting support.
- One issue is that I kept running into a duplicate trusted type issue with lit-html, so I needed to allow duplicates, but not sure if that's a good thing or not.
- This is an example workaround for the markdown issue that requires four indents for nested lists: https://github.com/google/mesop/issues/665
- Also curious to test this out with mel.chat  (replacing the me.markdown with this element) (https://github.com/google/mesop/issues/591)
> Add example webcomponent that uses markedjs, highlightjs, and mermaidjs

- mesop/components/uploader/BUILD
Otherwise, this breaks the downstream sync.
FYI: @richard-to
> Use py_library from defaults.bzl

- mesop/web/src/services/theme_service.ts
- mesop/web/src/shell/shell.ts
Using proto enum type directly in TS causes an issue in the downstream sync because the upstream and downstream representation of TS enums differs.
> Do not use TS theme mode proto enum type directly

- mesop/web/src/services/BUILD
- mesop/web/src/services/theme_service.ts
Turns out https://github.com/google/mesop/commit/f23e8b39918c59c04ef9b62fc8272e512c7d9d61 wasn't needed and I just needed to clean up unused imports
> Remove unused imports from theme_service.ts

- mesop/dataclass_utils/dataclass_utils.py
- mesop/dataclass_utils/dataclass_utils_test.py
Aligns the error message with https://github.com/python/cpython/blob/7797182b78baf78f64fe16f436aa2279cf6afc23/Lib/dataclasses.py#L861
> Note: should investigate whether to make the hashable check the same.
This makes the downstream sync smoother but seems like a good general improvement.
> Align dataclass_utils.py mutable type error message with py 3.11 standard lib error message

- mesop/runtime/runtime.py
For unclear reasons `colab_utils.is_running_ipython` does not work when running inside Runtime#create_context, possibly because the Mesop app server is running in a background thread?
> Fix #694 - only check debug mode for has served traffic check

- mesop/features/page.py
This prevents mutating security-sensitive configurations based on user input, e.g.
```py
security_policy = me.SecurityPolicy(...)
@me.page(security_policy=security_policy):
def page():
me.button(on_click=on_click)
def on_click(e):
security_policy.allowed_script_srcs = me.state(State).user_inputs
```
> Deep copy page configurations to prevent security-sensitive mutations

- mesop/examples/web_component/BUILD
- mesop/examples/web_component/__init__.py
- mesop/examples/web_component/copy_to_clipboard/BUILD
- mesop/examples/web_component/copy_to_clipboard/copy_to_clipboard_app.py
- mesop/examples/web_component/copy_to_clipboard/copy_to_clipboard_component.js
- mesop/examples/web_component/copy_to_clipboard/copy_to_clipboard_component.py
One issue trying to implement a copy command is that it does not work in Safari. Safari requires a user action, such as a click unfortunately.
The other option here is to use web component with a slot and click event, which apparently does work in Safari.
This web component also expects the browser has the  navigator.clipboard function.
Ref: https://github.com/google/mesop/issues/224
Ref: https://github.com/google/mesop/issues/275
> Add copy to clipboard web component

- mesop/examples/web_component/code_mirror_editor/code_mirror_editor_app.py
- mesop/examples/web_component/copy_to_clipboard/copy_to_clipboard_app.py
- mesop/examples/web_component/custom_font_csp_repro/custom_font_app.py
- mesop/examples/web_component/firebase_auth/firebase_auth_app.py
- mesop/examples/web_component/plotly/plotly_app.py
- mesop/examples/web_component/quickstart/counter_component_app.py
- mesop/examples/web_component/shared_js_module/shared_js_module_app.py
- mesop/examples/web_component/slot/slot_app.py
- mesop/labs/web_component.py
- mesop/protos/ui.proto
- mesop/runtime/context.py
- mesop/runtime/runtime.py
- mesop/server/constants.py
- mesop/server/server.py
- mesop/server/static_file_serving.py
- mesop/tests/e2e/web_components/csp_violations_test.ts
- mesop/tests/e2e/web_components/shared_js_module_test.ts
- mesop/web/src/app/editor/index.html
- mesop/web/src/app/prod/index.html
- mesop/web/src/services/channel.ts
- mesop/web/src/shell/shell.ts
I discovered an issue with the way we're loading JS modules for web components where _all_ the pages of the app will try to load the JS modules. This leads to either: a) unnecessarily loading JS modules or b) getting spammed with CSP errors because the other pages (which don't load the web component) will probably not have the right security policy (CSP) configuration. b) was happening on our own demo site.
This loads JS modules dynamically when a web component is called in a render loop. Note: JS module imports should be de-duped so re-importing the same module returns the same instance and is basically instant.
**Breaking change:** This PR introduces a breaking change for Mesop app developers using web components. You may  need to add sites to: …
> Load JS modules for web components as-needed [BREAKING CHANGE]

- mesop/server/static_file_serving.py
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-allowed-iframe-parents.txt
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-escaping.txt
- mesop/tests/e2e/snapshots/web_security_test.ts_csp.txt
- mesop/utils/terminal_colors.py
Fixes #566. This makes it a lot easier to fix CSP errors by printing a helpful message in the terminal. Particularly helpful with #723. 
**Screenshot:**
> Provide helpful terminal messages to fix web component CSP errors

- mesop/server/server.py
- mesop/web/src/services/channel.ts
This avoids potential naming collisions and establishes a convention that routes Mesop sets up are named: `/__{MESOP_ROUTE}__`.
> Change internal routes to prefix and postfix with "__"

- docs/guides/auth.md
Following the steps [here](https://google.github.io/mesop/guides/auth/), I was unable to deploy the app until I added `firebase-admin` to the `requirements.txt` file.
I might have missed this elsewhere in the docs!
> Adds note on adding `firebase-admin` to `requirements.txt`, in the `Auth` guide

- demo/dialog.py
- demo/snackbar.py
- mesop/component_helpers/style.py
- mesop/protos/ui.proto
- mesop/web/src/utils/styles.ts
- Updates snackbar example to use pointer events property
- Updates dialog to use place-items
- Closes #629
- Closes #731
> Add pointer-events and place-items to styles.

- mesop/web/src/shell/shell.ts
This makes the downstream sync easier
> Remove catch clause for dynamic import promise (use default browser console error messages)

- mesop/examples/__init__.py
- mesop/examples/navigate_absolute.py
- mesop/server/server.py
- mesop/tests/e2e/navigation_test.ts
- mesop/web/src/shell/shell.ts
> Allow absolute URL navigation

- docs/api/query_params.md
- mesop/__init__.py
- mesop/commands/BUILD
- mesop/commands/navigate.py
- mesop/examples/__init__.py
- mesop/examples/query_params.py
- mesop/features/BUILD
- mesop/features/query_params.py
- mesop/features/query_params_test.py
- mesop/protos/ui.proto
- mesop/runtime/BUILD
- mesop/runtime/context.py
- mesop/server/BUILD
- mesop/server/server.py
- mesop/tests/e2e/query_params_test.ts
- mesop/utils/url_utils.py
- mesop/utils/url_utils_test.py
- mesop/web/src/services/channel.ts
- mesop/web/src/shell/shell.ts
- mesop/web/src/utils/query_params.ts
- mesop/web/src/utils/query_params_spec.ts
- mkdocs.yml
- playwright.config.ts
Fixes #340.
This provides query param support using a dict-like API with inspiration from the [Web API](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) and [Streamlit's API](https://docs.streamlit.io/develop/api-reference/caching-and-state/st.query_params#stquery_paramsget_all).
> Support query params

- docs/guides/interactivity.md
- mesop/examples/__init__.py
- mesop/examples/async_await.py
- mesop/runtime/context.py
- mesop/tests/e2e/async_await_test.ts
Partially addresses #623. 
This allows using defining event handlers as async generators so that Mesop app developers can use `await`.
> Support async await in event handlers

- docs/comparison.md
- docs/faq.md
- mkdocs.yml
> Add a framework comparison doc

- mesop/web/src/component_renderer/component_renderer.ts
- mesop/web/src/editor/editor.ts
- mesop/web/src/services/BUILD
- mesop/web/src/services/error_dialog_service.ts
- mesop/web/src/shell/shell.ts
- scripts/cli_prod.sh
Fixes #729.
Only displays the dialog in debug mode. In prod mode, logs console error.
> Show an error dialog if web component is not registered

- mesop/component_helpers/helper.py
- mesop/component_helpers/helper_test.py
- mesop/examples/web_component/BUILD
- mesop/examples/web_component/__init__.py
- mesop/examples/web_component/complex_props/BUILD
- mesop/examples/web_component/complex_props/complex_props_app.py
- mesop/examples/web_component/complex_props/web_component.js
- mesop/examples/web_component/complex_props/web_component.py
- mesop/examples/web_component/slot/outer_component.js
- mesop/examples/web_component/slot/outer_component.py
- mesop/tests/e2e/web_components/complex_props_test.ts
- mesop/web/src/component_renderer/component_renderer.ts
- mesop/web/src/component_renderer/component_renderer_spec.ts
Fixes #730.
**Breaking change**: Web components are now set via DOM properties and not attributes. This means you can _not_ use Lit's attribute API, e.g. 
```ts
static properties = {
value: {type: Number},
incrementEventHandlerId: {attribute: 'increment-event', type: String},
};
```
I mixed up [DOM attributes and DOM properties](https://jakearchibald.com/2024/attributes-vs-properties/#value-types:~:text=elements%2C%20not%20properties.-,Value%20types,-In%20order%20to) and only primitive types, e.g. string, number, boolean, worked when I erroneously set the web component properties as DOM attributes. [Lit's default converter](https://lit.dev/docs/components/properties/#conversion-type) worked for the primitive types.
> Set web component as properties, not attributes [breaking change]

- ai/docbot/docs_index.py
- ai/docbot/eval_viewer.py
drive-by: make eval viewer easier to view for large inputs
> Fix up docbot - pass llm arg for QueryFusionRetriever

- mesop/examples/web_component/slot/counter_component.js
- mesop/examples/web_component/slot/outer_component.js
- mesop/examples/web_component/slot/slot_app.py
- mesop/tests/e2e/web_components/slot_test.ts
- mesop/web/src/component_renderer/component_renderer.ts
- playwright.config.ts
Fixes #449.
Drive-by: deflake the existing slot test by adding in `await`.
> Proper child reconciliation for web components with slots.

- mesop/component_helpers/helper.py
pylance was complaining about the type of `handler_fn` not being compatible with `wrap_handler_with_event`.
> Tighten event type in `register_event_handler`

- mesop/examples/async_await.py
- mesop/runtime/context.py
- mesop/tests/e2e/async_await_test.ts
Allows you to elide a solitary final 'yield' from async event handlers that don't stream responses, which seems more ergonomic.
> Support non-generating coroutines as event handlers.

- mesop/components/uploader/uploader.ng.html
- mesop/components/uploader/uploader.ts
- Slight breaking UI change since the "No file chosen" and filename labels have been removed. They were kind of redundant
- The user can add the labels themselves if necessary. This gives more flexibility
- Also resolves the issue of the filename not being reset.
- Closes #764 (User mainly wanted to change the label to remove it)
- Closes #739 (User wanted to reset the file chosen label after a file was selected)
> [UI change] Remove label for uploader button.

- docs/api/config.md
Just a small fix, I noticed earlier today when chatting with docs bot. Thought docs bot was wrong, but turns out it was my fault...lol.
> Add MESOP_STATE_SESSION_BACKEND_SQL_CONNECTION_URI to config docs.

- ai/docbot/deploy_to_hf.sh
- ai/docbot/pyproject.toml
- ai/docbot/requirements.txt
- ai/docbot/uv.lock
Our build started breaking today because llama-index packages had a version bump which causes an exception and broke docbot:
```
Traceback (most recent call last):
File "/home/runner/work/mesop/mesop/ai/docbot/docs_index.py", line 144, in <module>
llm = Gemini(model="models/gemini-1.5-flash-latest")
File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/llama_index/llms/gemini/base.py", line 149, in __init__
supported_methods = self._model_meta.supported_generation_methods
File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pydantic/main.py", line 807, in __getattr__
return self.__pydantic_private__[item]  # type: ignore
File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pydantic/main.py", line 825, in __getattr__
return …
```
> Migrates ai/docbot to uv to manage dependencies

- mesop/component_helpers/helper.py
- mesop/examples/__init__.py
- mesop/examples/functools_partial.py
- mesop/tests/e2e/functools_partial_test.ts
> Support functools.partial for event handlers

- mesop/web/src/app/styles.scss
- mesop/web/src/editor_toolbar/editor_toolbar.ng.html
- mesop/web/src/editor_toolbar/editor_toolbar.scss
- mesop/web/src/editor_toolbar/editor_toolbar.ts
- mesop/web/src/editor_toolbar/editor_toolbar_autocomplete_service.ts
- mesop/web/src/editor_toolbar/highlight_pipe.ts
Mixture of canned suggestions and history (only for the current browser session).
> Create autocomplete for editor toolbar

- ai/services/service.py
- mesop/server/server.py
- mesop/web/src/editor_toolbar/code_mirror_component.ts
- mesop/web/src/editor_toolbar/editor_history_dialog.ng.html
- mesop/web/src/editor_toolbar/editor_response_dialog.ng.html
- mesop/web/src/editor_toolbar/editor_send_prompt_progress_dialog.ng.html
- mesop/web/src/editor_toolbar/editor_toolbar.ts
- mesop/web/src/editor_toolbar/editor_toolbar_service.ts
- package.json
- yarn.lock
- Streams token to the UI while generating code for UI - this makes the UX a bit more pleasant since you can start reviewing the code right away.
- Switches the final dialog for approving the code changes to use unified diff view to match the intermediate UI a bit more (there's a slightly jarring scroll reset, but it seems unavoidable given that even if we reused the same dialog, it might not be correct to use the current scroll position).
> Stream generate response to UI

- mesop/examples/web_component/BUILD
- mesop/examples/web_component/__init__.py
- mesop/examples/web_component/async_action/BUILD
- mesop/examples/web_component/async_action/async_action_app.py
- mesop/examples/web_component/async_action/async_action_component.js
- mesop/examples/web_component/async_action/async_action_component.py
- mesop/examples/web_component/hotkeys/BUILD
- mesop/examples/web_component/hotkeys/hotkeys_app.py
- mesop/examples/web_component/hotkeys/hotkeys_component.js
- mesop/examples/web_component/hotkeys/hotkeys_component.py
Now that the child components issue has been fixed (https://github.com/google/mesop/issues/449), the hotkeys web component that I was working on a few weeks ago is working now.
Also adding the async action web component example.
> Add hotkeys and async action web component examples.

- demo/llm_rewriter.py
- mesop/labs/chat.py
Also update llm rewriter to match.
Closes #727
> Remove use of 100vh from chat component

- showcase/main.py
I added Mesop App Maker to to Hugging Face. It's not ideal, since users need to create their own runner in Hugging Face Spaces. It's prettty easy to do. Just need to duplicate the Mesop App Runner space and set a "runner token". The runner token is just a basic way to block people from randomly using other people's runner instances.
Also added a link to the Hugging Face Jeopardy Mesop app.
> Adds app url for mesop app maker.

- docs/internal/development.md
- scripts/pip.sh
This makes it much faster for iterating.
Other drive-by changes:
- This also tells the user to run: `source /tmp/mesoprelease-test/venv-test/bin/activate` after the script is done because it doesn't seem to carry over when the command is run within the script (not exactly sure why).
- Instead of running `mesop main.py` we print out the command since usually I like to open the editor in that directory first to test out hot reloading (e.g. `code .`)
> Make pip.sh faster with `uv` and easier to use with explicit steps

- mesop/web/src/editor_toolbar/editor_toolbar.ts
Previously there was a bug where if you unselected a component (e.g. using ESC hotkey), then the editor toolbar would erroneously continue to use the previously selected component for the prompt context.
> Fix selected component logic in editor toolbar

- ai/ft/dataset_formatter.py
- ai/services/service.py
I forgot to check-in this change earlier to reduce our prompt context for the ft dataset.
> Use smaller prompt context for new ft model

- showcase/deploy_to_hf.sh
For some reason it seems like there's a difference when running locally on Mac vs. when running on GitHub Actions on Linux, not exactly sure why.
> Fix deployment script for showcase

- ai/src/service.py
- mesop/web/src/editor_toolbar/editor_history_dialog.ng.html
- mesop/web/src/editor_toolbar/editor_response_dialog.ng.html
- mesop/web/src/editor_toolbar/editor_toolbar.ng.html
- mesop/web/src/editor_toolbar/editor_toolbar.scss
- mesop/web/src/editor_toolbar/editor_toolbar.ts
- mesop/web/src/editor_toolbar/editor_toolbar_service.ts
Minor fixes in service.py:
- Fix path issue after refactoring
- Make the saved interaction folder name nicer
Many smallish changes for editor toolbar:
- Update response dialog title and swap buttons so OK/apply is default
- Close the autocomplete panel correctly after the progress dialog is closed
- Swap button order for revert dialog to be consistent
- Add history entry after reverting
- Remove drag icon (the whole toolbar is draggable)
- Make the toolbar more reasonably sized
- Add keyboard shortcut (command/ctrl+K) for editor toolbar textarea
> Polish editor toolbar and AI service

- mesop/component_helpers/style.py
> Style API tweaks

- docs/guides/server-integration.md
- mesop/server/wsgi_app.py
- mkdocs.yml
The FastAPI example seems to be working well:
https://github.com/wwwillchen/mesop-fastapi
However, I'm having trouble with the Flask example: https://github.com/wwwillchen/mesop-flask - when I try to run Mesop in debug mode, it's not loading.
All things considered though, I think encouraging people to use FastAPI is better as it reduces the likelihood of a version dependency conflict with Mesop's internal Flask usage and other people's Flask usage.
Fixes #803.
> Add docs for mounting Mesop app

- .github/workflows/ci.yml
- mesop/components/html/e2e/html_test.ts
- mesop/examples/e2e/theme_test.ts
- mesop/tests/e2e/e2e_helpers.ts
- mesop/tests/e2e/late_registration_error_test.ts
- mesop/tests/e2e/on_load_test.ts
- mesop/tests/e2e/viewport_size_test.ts
- mesop/tests/e2e/web_components/csp_violations_test.ts
- mesop/tests/e2e/web_security_test.ts
- playwright.config.ts
Long overdue, but we should run our e2e tests in both prod and debug/editor mode to catch regressions, especially with all the editor toolbar changes.
This skips some of the e2e tests in debug mode, particularly those related to web security, because we have more lax web security policies when running in debug mode. We could run those tests in debug mode and maintain separate goldens (e.g. for CSPs), but this is a bit of work and doesn't seem too pressing.
> Run e2e tests in debug/editor mode (in addition to prod mode)

- mesop/examples/__init__.py
- mesop/examples/scroll_into_view_deferred.py
- mesop/tests/e2e/scroll_into_view_test.ts
- mesop/web/src/shell/shell.ts
> Allow scroll_into_view to work for components rendered in the same tick

- ai/src/ai/offline_common/inputs/chat.py
- demo/fancy_chat.py
- demo/llm_rewriter.py
- mesop/examples/inlined_chat.py
- mesop/labs/chat.py
We can remove the intentional delay on scroll-to now.
There is one case where this does not work as expected though. When the chat message is not streamed, the scroll to with hidden box strategy does not work since the output is too fast. This occurred on LLM Rewriter example. But I updated it to fake the streaming.
Also decreases the size of the hidden box, so it is less jarring when the box disappears.
> Update some usages of scroll-to

- mesop/web/src/editor_toolbar/editor_toolbar.ts
I noticed that the Angular dialog sets a 65vh. But our code is using 80vh. So I set it to 65vh to match.
One consideration though is whether this 65vh changes dynamically or not. I did try adjusting viewport sizes in Chrome dev tools and it seemed like it stayed at 65vh but not sure.
Closes #908
> Fix cutoff content for history prompt list / code diff viewer

- demo/dialog.py
- mesop/component_helpers/helper.py
- mesop/components/button/button.ts
- mesop/events/events.py
- mesop/examples/testing/__init__.py
- mesop/examples/testing/click_is_target.py
- mesop/protos/ui.proto
- mesop/tests/e2e/click_is_target_test.ts
- mesop/web/src/component_renderer/component_renderer.ts
Usage of is_target mainly works for me.box.
For me.button / me.content_button it will almost always be false since the buttons are composed of other sub elements. There may be cases where it is true.
Updated dialog usages to utilize `is_target`.
Closes #268
> Add is_target to Click event

- mesop/runtime/runtime.py
Adding this method for downstream usage integration.
> Add get_path_to_page_configs

- mesop/components/autocomplete/autocomplete.py
- mesop/components/autocomplete/e2e/autocomplete_app.py
Forgot to remove this when creating the autocomplete component initially.
The require_selection property overall is not too helpful for Mesop. The require_selection can be implemented in Mesop by just using the AutocompleteSelectionChangeEvent when populating valid option values.
> Remove require_selection from autocomplete

- package.json
- yarn.lock
Fixes the issue with running on recent macOs upgrade (need to run: `yarn playwright install chromium --with-deps` after upgrade)
> Upgrade playwright

- mesop/dataclass_utils/BUILD
- mesop/dataclass_utils/dataclass_utils.py
- mesop/dataclass_utils/dataclass_utils_test.py
- mesop/dataclass_utils/diff_state_test.py
- mesop/examples/__init__.py
- mesop/examples/pydantic_state.py
- mesop/tests/e2e/pydantic_state_test.ts
- mesop/web/src/utils/diff.ts
- mesop/web/src/utils/diff_state_spec.ts
> Support pydantic BaseModel classes in state

- demo/bootstrap.py
- demo/main.py
- mesop/components/box/box.proto
- mesop/components/box/box.py
- mesop/editor/component_configs.py
- mesop/examples/__init__.py
- mesop/examples/tailwind.py
- mesop/web/src/app/styles.scss
- mesop/web/src/component_renderer/component_renderer.ts
- mesop/web/src/dev_tools/editor_panel/editor_panel.scss
- mesop/web/src/editor/editor.ng.html
- mesop/web/src/editor/editor.scss
Ref: https://github.com/google/mesop/issues/438
> Add CSS class support for box component

- mesop/components/datepicker/e2e/datepicker_test.ts
Update the test so that when the month changes, the test won't break.
In this case, if there is an invalid date, opening the calendar will show the current day.
> Fix broken datepicker test

- mesop/server/server.py
> Add X-Accel-Buffering header to SSE responses

- mesop/tests/e2e/event_handler_error_test.ts
- mesop/web/src/error/error_box.ng.html
- mesop/web/src/error/error_box.scss
- mesop/web/src/error/error_box.ts
- mesop/web/src/shell/shell.ng.html
- mesop/web/src/shell/shell.ts
- Dialog provides a more standard UI compared to the somewhat strange fullscreen error box (it's easier to dismiss it and it's clearer from the overlay that there's, potentially, still UI that you can interact with).
- Stop automatically hiding the error UI if there's no more errors in the next render; instead we will close the previous error dialog if there's a new error. 
- The problem with the previous approach of automatically hiding is that if you're streaming a response, the first chunk could through an error, but the second chunk might not, which results in a flash of the error UI even though the error is still in the code.
> Turn (server) error box into a more standard dialog UI

- demo/sidenav.py
- mesop/__init__.py
- mesop/components/sidenav/e2e/__init__.py
- mesop/components/sidenav/e2e/sidenav_app.py
- mesop/components/sidenav/e2e/sidenav_app_no_esc.py
- mesop/components/sidenav/e2e/sidenav_app_position.py
- mesop/components/sidenav/e2e/sidenav_test.ts
- mesop/components/sidenav/sidenav.ng.html
- mesop/components/sidenav/sidenav.proto
- mesop/components/sidenav/sidenav.py
- mesop/components/sidenav/sidenav.ts
Changes:
- Add on opened change event handler (so user can update state) when escape pressed
- Add disable_close property to prevent escape from being used
- Drive bys:
- Add position property so sidenav can be rendered on the right side
- Minor style adjustments to sidenav demo
Closes #1019
> Fix sidenav "escape" key bug

- mesop/labs/web_component.py
In the [web_component.py](https://github.com/google/mesop/blob/main/mesop/labs/web_component.py#L34-L35) file, an os specific path is constructed at [line 33](https://github.com/google/mesop/blob/main/mesop/labs/web_component.py#L33) using `os.path.join`. 
But immediately the path is checked whether it starts with "/" or not. "/" is a linux specific path separator and ideally the code should use os specific path separator. 
This PR fixes that issue.
Because of this issue, in windows, full_path `\some\dir\file.js` becomes `/\some\dir\file.js` and later when converted to a URL it becomes `http://host:port//some/dir/file.js` which is not really a valid URL.
> Use OS specific path separator

- docs/api/config.md
- mesop/cli/cli.py
- mesop/env/BUILD
- mesop/env/env.py
- mesop/examples/__init__.py
- mesop/examples/concurrent_updates_websockets.py
- mesop/runtime/BUILD
- mesop/runtime/context.py
- mesop/runtime/runtime.py
- mesop/server/BUILD
- mesop/server/server.py
- mesop/server/server_debug_routes.py
- mesop/server/server_utils.py
- mesop/server/wsgi_app.py
- mesop/tests/e2e/concurrent_updates_websockets_test.ts
- mesop/tests/e2e/e2e_helpers.ts
This follows up from #1027 and it reuses the same Context instance for an entire session (i.e. websockets connection). This fixes the edge case in #1028 because the component diffing bug is fixed. See new test case which covers this.
I've extracted the environmental variables from `server/server_utils.py` into a separate package `env` to avoid cyclic dependencies since many packages like `runtime` may want to depend on `env`.
> Add proper concurrency support in websockets mode

- build_defs/defaults.bzl
- build_defs/requirements.txt
- build_defs/requirements_lock.txt
- docs/api/config.md
- mesop/cli/cli.py
- mesop/runtime/runtime.py
- mesop/server/BUILD
- mesop/server/server.py
- mesop/server/wsgi_app.py
- mesop/web/src/services/BUILD
- mesop/web/src/services/channel.ts
- package.json
- yarn.lock
Based on a suggestion from a co-worker who used socket.io quite a bit, it's quite a lot of hassle (e.g. protocol version compatibility) compared to using vanilla websocket since we don't need to use an HTTP fallback in our use case.
Notes:
- Uses the native WebSockets API on the client-side and [flask-sock](https://github.com/miguelgrinberg/flask-sock) which is a modern successor to [flask-socketio](https://github.com/miguelgrinberg/flask-socketio) (note: same author)
- Creates a UUID for the session (i.e. WebSockets lifetime) so that we can reuse the same Context instance across multiple user events (this is the same behavior as introduced in #1036, but using a different mechanism because flask-sock doesn't include `request.sid`)
- Launches a background thread _with_ the Flask request …
> Switch from socket.io to vanilla websockets & fix state updates for websockets

- .github/workflows/ci.yml
- demo/main.py
- demo/static/tailwind.css
- demo/tailwind.py
- docs/api/config.md
- docs/guides/static-assets.md
- mesop/BUILD
- mesop/examples/__init__.py
- mesop/server/config.py
- mesop/server/server.py
- mesop/static/tailwind.css
- mesop/tests/e2e/static_folder_test.ts
- mkdocs.yml
- playwright.config.ts
Flask allows a static assets directory be specified. It turns out this can be an absolute path or a relative path.
I'm not sure if I'm doing the relatively path part correctly for bazel or the pip version.
This is not completed yet. Still need to add docs, tests. But mainly just wanted to see if this is reasonable.
One issue is that specifying the stylesheet from the page object in terms of CSP:
```
The source list for the Content Security Policy directive 'style-src' contains an invalid source: '/assets/tailwind.css'. It will be ignored.
```
Interestingly the CSS seems to be still read correctly.
Ref: https://github.com/google/mesop/issues/960
> Add option expose static folder

- .vscode/settings.json
- mesop/examples/testing/__init__.py
- mesop/examples/testing/csp_escaping.py
- mesop/examples/testing/csp_trusted_types.py
- mesop/features/page.py
- mesop/security/BUILD
- mesop/security/security_policy.py
- mesop/security/security_policy_test.py
- mesop/server/static_file_serving.py
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-escaping.txt
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-trusted-types.txt
- mesop/tests/e2e/web_security_test.ts
> Add additional parameters for SecurityPolicy: trusted types and worker src

- mesop/examples/query_params.py
- mesop/tests/e2e/query_params_test.ts
- mesop/web/src/services/channel.ts
- mesop/web/src/shell/shell.ts
Previously we had an edge case where a navigate & query param mutation (see newly added e2e test case) ran into a race condition because we weren't properly awaiting the Angular router navigation.
This ensures that all commands (including across render events) are processed serially.
> Fix race condition in processing commands (navigate)

- demo/select_demo.py
- mesop/components/select/e2e/select_test.ts
- mesop/components/select/select.ts
Seems like in single select mode, the ngModel is a string rather than an array.
So we need to update the code to handle both cases.
Closes #1071
> Fix bug with single select value not showing.

- mesop/server/server.py
This fixes a race condition in websockets mode by disabling component diffing.
> Disable component diffing when MESOP_WEBSOCKETS_ENABLED

- mesop/server/server.py
This should fix the error I was getting in websockets mode:
```
ValueError: <Token var=<ContextVar name='flask.request_ctx' at 0x102d56c50> at 0x1138dbac0> was created in a different Context
```
See: https://github.com/pallets/flask/discussions/5254
> Move copy_current_request_context to ensure thread-safety

- .github/workflows/ci.yml
- docs/api/config.md
- mesop/env/env.py
- mesop/examples/BUILD
- mesop/examples/__init__.py
- mesop/examples/app_base/BUILD
- mesop/examples/app_base/__init__.py
- mesop/examples/app_base/main.py
- mesop/examples/app_base/static/test.txt
- mesop/labs/web_component.py
- mesop/server/server_utils.py
- mesop/server/static_file_serving.py
- mesop/tests/e2e/app_base_test.ts
This adds MESOP_APP_BASE_PATH as a new configuration via env var to support the use case where `os.getcwd()` cannot be reliably used as the app base path. Specifically, if you want to build a pip package CLI app that runs Mesop, using the cwd isn't feasible because the app user can be running the CLI command from an arbitrary directory (and not the mesop app directory). I suspect this is a pretty niche use case so I don't think most people will need to use this.
Note: the testing for this isn't that great (it's not trivial to cover the pip CLI use case with our current integration test infra), but it covers the static folder case.
> Add env var: MESOP_APP_BASE_PATH 

- mesop/protos/ui.proto
- mesop/server/server.py
- mesop/server/static_file_serving.py
- mesop/version.py
- mesop/web/src/app/editor/index.html
- mesop/web/src/app/prod/index.html
- mesop/web/src/services/channel.ts
- mesop/web/src/services/experiment_service.ts
It's better to send the experiment settings on initial page load rather than getting them from the first render, particularly for the websockets configuration because it can result in a weird edge case where the first UI request is over SSE (HTTP) and all the subsequent requests is over WebSockets. Because Mesop has very different behavior under WebSockets (e.g. state is kept in-memory and never sent over the network) compared to SSE, mixing SSE and WebSockets over a single browser session can result in weird edge cases.
> Send experiment settings on initial page load

- mesop/commands/navigate.py
- mesop/tests/e2e/query_params_test.ts
The previous implementation had a flaw where it issued a command to clear the query params which resulted in replacing the browser history entry, which means that back navigations would not restore the original query params. (The e2e test case demonstrates this issue).
> Fix clearing query params when navigating

- mesop/runtime/context.py
- mesop/runtime/runtime.py
- mesop/server/server.py
This skips the trace mode render loop in WebSockets mode which is a significant perf improvement, since we can use the last render loop because the Context is long-lived across multiple UI requests (for the same session).
This always registers the event handler regardless of whether we're in trace mode. For non-WebSockets mode, there's no practical difference.
> Skip unnecessary trace render loop in WebSockets mode

- mesop/features/query_params_test.py
- mesop/runtime/context.py
- mesop/runtime/runtime.py
> Remove unused handler code from Runtime/Context

- mesop/server/static_file_serving.py
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-allowed-iframe-parents.txt
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-escaping.txt
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-trusted-types.txt
- mesop/tests/e2e/snapshots/web_security_test.ts_csp.txt
For example, if you use mux.com, their mux player will try to load the video from the blob origin.
> Allow blob as a valid origin for img/media

- mesop/components/expansion_panel/e2e/expansion_panel_app.py
- mesop/components/expansion_panel/e2e/expansion_panel_test.ts
- mesop/components/expansion_panel/expansion_panel.ng.html
Fixes #1128 (see screenshots for before-after)
> Do not render expansion panel description if unused

- mesop/version.py
- mesop/web/src/component_renderer/component_renderer.ts
If you navigate to the same pages over and over again, you can measure an significant increase in JS memory (heap snapshots). The main contributor was that we weren't cleaning up the embedded view refs.
> Fixes major memory leak in component renderer

- mesop/web/src/app/editor/BUILD
- mesop/web/src/app/editor/bundle.ts
- mesop/web/src/app/editor/index.html
- mesop/web/src/editor/BUILD
- mesop/web/src/editor/editor.ts
I was over-zealous in #1135 which ended up breaking hot reload. I've restored the editor module to restore hot reload and also not break the downstream sync which has specific hooks on editor.
> Restore hot reload functionality

- mesop/web/src/editor/editor.ts
Accidentally removed in #1135.
See [#68 ](https://github.com/google/mesop/issues/68#issuecomment-2525334141)
> Restore hot reload keyboard shortcut

- README.md
Repair broken links in README.md file
> Fix broken demo and security links in README.md

- mesop/component_helpers/helper.py
I checked @component again and that seems to work. It was only @content_component which was not showing the type hints.
Not sure why removing the annotation made it so thecustom component's annotations showed up.
Closes #912
> Fix missing type hints for @content_component

- docs/api/config.md
Accidentally spelled it incorrectly in the docs (I forgot whether websockets is one or two words :()
> Fix typo for MESOP_WEBSOCKETS_ENABLED docs

- docs/web-components/troubleshooting.md
Document workaround from #1152
> Add Colab workaround to web components troubleshooting docs

- tools/defaults.bzl
Our karma web test targets started breaking recently on GitHub Actions because, for some reason, we can longer launch Chrome browser in a sandbox (my guess is GitHub Actions VM have changed somehow).
This uses the standard Bazel Chromium browser target rather than Angular's specific one because the the new one includes "--no-sandbox".
> Update browser for karma targets

- docs/components/index.md
- mesop/__init__.py
- mesop/component_helpers/BUILD
- mesop/component_helpers/helper.py
- mesop/component_helpers/helper_test.py
- mesop/examples/__init__.py
- mesop/examples/e2e/complex_slots_test.ts
- mesop/examples/named_nested_slot.py
- mesop/examples/testing/__init__.py
- mesop/examples/testing/complex_slots.py
- mesop/runtime/BUILD
- mesop/runtime/context.py
- mesop/runtime/node_tree_state_test.py
- Adds support for named slots
- Mostly fixes issues with custom components inside custom components
- Still has the limitation where you can't defer slot rendering to a higher level component
- Update docs
- 
- Closes https://github.com/google/mesop/issues/810
- Closes https://github.com/google/mesop/issues/929
> Named slots / Nested slots

- mesop/dataclass_utils/dataclass_utils.py
- mesop/dataclass_utils/dataclass_utils_test.py
See internal tracker for details.
> Harden dataclass utils

- mesop/env/env.py
- mesop/server/config.py
Looks like the issue is that env.py gets loaded before config.py since the latter contains the code to load the .env. We may want to combine env.py and config.py. But for now, just fixing the bug.
So basically the .env file was being loaded correctly. It just wasn't handling the env vars in env.py correctly which was why I could never enable web sockets. 
Closes #1180
> Make sure .env is loaded before env var are set

- mesop/web/src/shell/shell.ts
Finally got a chance to test out the afterRender suggestion. It seems to work.
Closes #1121
> Run scroll command via Angular afterRender hook

- .github/workflows/ci.yml
Notes: https://github.com/actions/upload-artifact
This fixes a non-unique artifact path which is enforced by upload-artifact@v4 (and is a good practice).
This pins it to a specific hash (which is best practice for security/reproducibility)
> Upgrade upload-artifact action because v3 is deprecated

- mesop/components/box/e2e/box_app.py
- mesop/components/box/e2e/box_test.ts
- mesop/web/src/component_renderer/component_renderer.ts
This keeps the current functionality `Box#on_click` but improves the performance on ComponentRenderer
I was noticing 30-45 ms spent on the click handler on my mesop app. It's particularly noticeable when there's a deep component hierarchy I think. 
This trims down the click handler to something much shorter ~10ms.
> Only add click listener when necessary on ComponentRenderer

- biome.json
- mesop/examples/web_component/BUILD
- mesop/examples/web_component/__init__.py
- mesop/examples/web_component/gemini_live/BUILD
- mesop/examples/web_component/gemini_live/audio_player.js
- mesop/examples/web_component/gemini_live/audio_player.py
- mesop/examples/web_component/gemini_live/audio_recorder.js
- mesop/examples/web_component/gemini_live/audio_recorder.py
- mesop/examples/web_component/gemini_live/demo.py
- mesop/examples/web_component/gemini_live/gemini_live.js
- mesop/examples/web_component/gemini_live/gemini_live.py
- mesop/examples/web_component/gemini_live/gemini_live_api.js
- mesop/examples/web_component/gemini_live/utils.py
- mesop/examples/web_component/gemini_live/video_recorder.js
- mesop/examples/web_component/gemini_live/video_recorder.py
Demonstrates the following:
- Setting up web socket connection to Gemini Live API via client
- Playing audio responses from Gemini Live API
- Sending audio input via user's microphone to Gemini Live API
- Sending video frames via user's webcam to Gemini Live API
- Using custom tool to interact with Mesop UI
> Add example of using Gemini Live API with Mesop.

- demo/main.py
- demo/tab_group.py
Punting on getting the Angular Material Tab component working for now.
So just creating a very barebones tab group as a starting point.
> Add a basic tab group demo

- mesop/server/static_file_serving.py
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-allowed-iframe-parents.txt
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-escaping.txt
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-trusted-types.txt
- mesop/tests/e2e/snapshots/web_security_test.ts_csp.txt
We should allow the self origin so people can self-host font files.
> Fix font-src CSP

- .github/workflows/ci.yml
Example of [failed run](https://github.com/google/mesop/actions/runs/13642334515/job/38134708555?pr=1215):
```
Download action repository 'angular/dev-infra@af6d1c371f387efd5703a24739412ea862c3218e' (SHA:af6d1c371f387efd5703a24739412ea862c3218e)
Download action repository 'pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507' (SHA:646c83fcd040023954eafda54b4db0192ce70507)
Download action repository 'actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08' (SHA:65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08)
Getting action download info
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: 704facf57e6136b1bc63b828d79edcd491f0ee84`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: …
```
> Bump GitHub actions workflow hash because it's outdated

- mesop/web/src/app/styles.scss
This keeps the same behavior between component-renderer (regular components) and component-renderer-element (used for web components)
> Add display: block for component-renderer-element

- mesop/examples/testing/__init__.py
- mesop/examples/testing/csp_font_srcs.py
- mesop/security/security_policy.py
- mesop/server/static_file_serving.py
- mesop/tests/e2e/snapshots/web_security_test.ts_csp-allowed-font-srcs.txt
- mesop/tests/e2e/web_security_test.ts
One example use case is when a stylesheet contains references to remote font files. These files will get blocked by CSP unless added to font-src
> Add support for font-src

- docs/components/text-to-text.md
- mesop/labs/text_to_text.py
I can't find any usage of text_io on GitHub - see https://sourcegraph.com/search?q=context:global++mel.text_io%28&patternType=keyword&sm=0
I think it's safe to remove this as we throw an error and it's pretty easy to migrate to text_to_text (one-line change)
> Upgrade text_io warning to error (prep for v1)

- showcase/main.py
Looks like they no longer use mesop
> Remove meta llama from showcase

- mesop/web/src/app/styles.scss
This also avoids an internal API migration
> Remove unused CSS for editor toolbar which has been unshipped

- demo/text_to_text.py
The demo for text_to_text is supposed to capitalize the input. It's actually correct in the readme but was wrong in the code.
> fix(demo): capitalize input in text-to-text example

- mesop/web/src/shell/shell.ts
`afterRenderEffect` is better suited here as it will only be executed when the signal changes.
Note: Angular intends to rename the `afterRender` api.
> refactor: remove `afterRender`

- demo/context_menu.py
- demo/main.py
- demo/static/context_menu.css
- mesop/__init__.py
- mesop/component_helpers/helper.py
- mesop/components/box/box.proto
- mesop/components/box/box.py
- mesop/components/box/e2e/__init__.py
- mesop/components/box/e2e/box_events_app.py
- mesop/components/box/e2e/box_events_test.ts
- mesop/components/button/button.proto
- mesop/components/button/button.py
- mesop/components/button/button.ts
- mesop/events/__init__.py
- mesop/events/events.py
- mesop/protos/ui.proto
- mesop/static/context_menu.css
- mesop/web/src/component_renderer/component_renderer.ts
- This change adds some new properties to the click event for getting x/y coordinates on click event
- Also adds a right click event that overrides contextmenu event (ended up making this a separate event so we know when to disable the contextmenu (though maybe could have used click event and added is_right_click)
- Also added simple example of a context menu in Mesop with a right click.
- Closes #1272 
- Closes #301
> Add coordinate values for click events + add right click event + add context menu example

- ai/docbot/docs_index.py
- ai/prompt_context/transform_txt.py
- demo/llm_playground.py
- docs/codelab/4.md
The 1.5 models are no longer usable, so update to 2.5 variants.
Closes #1307
> Update old Gemini 1.5 model references.
